(function(g){var window=this;'use strict';var jd0=async function(K,H,r){K.Y=g.At(H,r)},BJ=function(K){K.isActive()||K.start()},MN4=function(K,H){var r=new g.jC;
r.languageCode=K.languageCode;r.languageName=K.languageName;r.name=K.name;r.displayName=K.displayName;r.kind=K.kind;r.isDefault=!1;r.K=K.K;r.isTranslateable=K.isTranslateable;r.vssId=K.vssId;r.url=K.url;r.translationLanguage=H;K.xtags&&(r.xtags=K.xtags);K.captionId&&(r.captionId=K.captionId);return r},vJ=function(K,H){return H?K.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},BPS=function(K){return g.SR(K)||K.O("web_enable_caption_language_preference_stickiness")},vdL=async function(K,H){K=
K+"|"+H;
H=await g.d3();if(!H)throw g.qp("gct");return(await g.vo(H)).get("captions",K)},I4S=function(K,H,r){vdL(K,H).then(O=>{O&&r(O.trackData,new g.jC(O.metadata))})},IK=function(K){if(!ZSL.test(K))throw Error("'"+K+"' is not a valid hex color");
K.length==4&&(K=K.replace(FUB,"#$1$1$2$2$3$3"));K=K.toLowerCase();K=parseInt(K.slice(1),16);return[K>>16,K>>8&255,K&255]},eeq=function(){var K={},H="suggest_correction"in g.da?g.da.suggest_correction:"Edit caption";
H=H||"";for(let r in K){let O=()=>String(K[r]);
H=H.replace(new RegExp("\\$\\{"+r+"\\}","gi"),O);H=H.replace(new RegExp("\\$"+r,"gi"),O)}return H},Zs=function(){return g.Fu("yt-player-caption-display-settings")},od4=function(K,H){var r=g.eo(K.segments,H);
r>=0||r<0&&(-r-1)%2===1||(r=-r-1,r>0&&H-K.segments[r-1]===1&&r<K.segments.length&&K.segments[r]-H===1?(g.OQ(K.segments,r),g.OQ(K.segments,r-1)):r>0&&H-K.segments[r-1]===1?K.segments[r-1]=H:r<K.segments.length&&K.segments[r]-H===1?K.segments[r]=H:(g.Iq(K.segments,r,0,H),g.Iq(K.segments,r+1,0,H)))},X$G=function(K){return K.K&&K.K.V?K.K.V+K.player.Se()<K.player.getCurrentTime():!1},w$L=function(K,H){if(K.policy.r6&&K.player.FW()){var r=g.f2(H,K.policy,{});
r.set("pot",K.player.FW());r=r.nB()}else r=g.f2(H,K.policy,{}).nB();var O={format:"RAW",withCredentials:!0};if(K.policy.TF){O.method="POST";let b=H.N;b&&Object.keys(b).length>0?O.postBody=g.b6(b,g.XT):O.postBody=(0,g.FH)([120,0])}K.V&&(O.responseType="arraybuffer");var A=++K.Bn,k=(0,g.f)();K.Y=g.yi(r,O,3,100,-1,b=>{b.errorCode==="net.timeout"&&K.player.Yv("capnt",{rn:A++})}).then(b=>{if(K.policy.uL&&A%100===1){var D=(0,g.f)();
K.player.Yv("caprsp",{rn:A,ms:D-k,kb:(b.xhr.responseText.length/1024).toFixed()})}a:{b=b.xhr;K.Md();if(K.B){var y=!(K.V?b.response:b.responseText)||b.status>=400;if(D=g.XqN(b)){b=g.f2(K.B,K.policy,{});K.B.q0(b,D);w$L(K,K.B);break a}y?K.player.Yv("capfail",{status:b.status}):(g.xW("fcb_r",(0,g.f)(),K.player.getVideoData().SQ||""),D=K.B.E5[0],y=D.kv,K.j!=null&&K.W!==y&&(K.V?K.j(b.response,(D.segmentStartTime+K.player.Se())*1E3):K.j(b.responseText,(D.segmentStartTime+K.player.Se())*1E3),K.W=y))}K.B=
null;K.Y=null}}).pO(b=>{K.B=null;
K.Y=null;K.player.Yv("capfail",{rn:A,status:b.xhr?.status})});
K.B=H;od4(K.N,K.B.E5[0].kv)},dmL=function(K,H){return H!=null&&H in K.Y.K?K.Y.K[H]:null},cd0=function(K,H,r){var O=[];
for(let A in K.Y.K){if(!K.Y.K.hasOwnProperty(A))continue;let k=K.Y.K[A];if(g.R7(k,r||null)){let b=k.info.captionTrack;b&&b.languageCode===H&&O.push(k)}}return O.length?O[0]:null},TPo=function(K,H){var r=[];
for(let A in K.Y.K){if(!K.Y.K.hasOwnProperty(A))continue;var O=K.Y.K[A];if(g.R7(O,H||null)){let k=O.info.id,b=k,D=`.${k}`,y="",B="";if(O=O.info.captionTrack)k=O.languageCode,b=O.displayName,D=O.vssId,y=O.kind,B=O.id;r.push(new g.jC({id:A,languageCode:k,languageName:b,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:D,kind:y,captionId:B}))}}return r},QdS=function(K,H,r,O){var A=H/360*16;
H>=K&&(K=640,O>r*1.3&&(K=480),A=r/K*16);return A},Edx=function(K){var H=1+.25*(K.fontSizeIncrement||0);
if(K.offset===0||K.offset===2)H*=.8;return H},$mu=function(K,H){var r="vertical-rl";
K.K.yh===1&&(r="vertical-lr");g.wb&&(r=r==="vertical-lr"?"tb-lr":"tb-rl");g.Ut(H,"-o-writing-mode",r);g.Ut(H,"-webkit-writing-mode",r);g.Ut(H,"writing-mode",r);g.Ut(H,"text-orientation","upright");g.DB(H,"ytp-vertical-caption");K.Y.params.M3===3&&(g.Ut(H,"text-orientation",""),g.Ut(H,"transform","rotate(180deg)"))},xmG=function(K,H){var r={},O=H.background?H.background:K.K.zZ.background;
if(H.backgroundOpacity!=null||H.background){var A=H.backgroundOpacity!=null?H.backgroundOpacity:K.K.zZ.backgroundOpacity;O=IK(O);r.background="rgba("+O[0]+","+O[1]+","+O[2]+","+A+")";K.hy&&(r["box-decoration-break"]="clone",r["border-radius"]=`${K.ZE*.25}px`)}if(H.fontSizeIncrement!=null||H.offset!=null)r["font-size"]=`${K.Jy*Edx(H)}px`;K.experiments.cn("enable_player_captions_new_style_defaults")&&(r["line-height"]="1.375");O=1;A=H.color||K.K.zZ.color;if(H.color||H.textOpacity!=null)A=IK(A),O=H.textOpacity==
null?K.K.zZ.textOpacity:H.textOpacity,A="rgba("+A[0]+","+A[1]+","+A[2]+","+O+")",r.color=A,r.fill=A;var k=H.charEdgeStyle;k===0&&(k=void 0);if(k){A=`rgba(34, 34, 34, ${O})`;let y=`rgba(204, 204, 204, ${O})`;H.uK&&(y=A=H.uK);let B=K.Jy/16/2,Z=Math.max(B,1);var b=Math.max(2*B,1),D=Math.max(3*B,1);let F=Math.max(5*B,1);O=[];switch(k){case 4:for(;D<=F;D+=B)O.push(`${b}px ${b}px ${D}px ${A}`);break;case 1:b=window.devicePixelRatio>=2?.5:1;for(k=Z;k<=D;k+=b)O.push(`${k}px ${k}px ${A}`);break;case 2:O.push(`${Z}px ${Z}px ${y}`);
O.push(`-${Z}px -${Z}px ${A}`);break;case 3:for(D=0;D<5;D++)O.push(`0 0 ${b}px ${A}`)}r["text-shadow"]=O.join(", ")}A="";switch(H.fontFamily){case 1:A='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", serif-monospace, monospace';break;case 2:A='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:A='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", sans-serif-monospace, monospace';break;case 5:A='"Comic Sans MS", Impact, Handlee, fantasy';break;
case 6:A='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:A=g.$g()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:A='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}A&&(r["font-family"]=A);A=H.offset;A==null&&(A=K.K.zZ.offset);switch(A){case 0:r["vertical-align"]="sub";break;case 2:r["vertical-align"]="super"}H.fontFamily===7&&(r["font-variant"]=
"small-caps");H.bold&&(r["font-weight"]="bold");H.italic&&(r["font-style"]="italic");H.underline&&(r["text-decoration"]="underline");H.PR&&(r.visibility="hidden");H.Mu===1&&K.N&&(r["text-combine-upright"]="all",r["text-orientation"]="mixed",A=g.z0||g.nn,K.Y.params.M3===3?r.transform=A?"rotate(90deg)":"rotate(180deg)":A&&(r.transform="rotate(-90deg)"));if(H.textEmphasis===1||H.textEmphasis===2||H.textEmphasis===3||H.textEmphasis===4||H.textEmphasis===5)if(g.z0)r["font-weight"]="bold";else switch(r["text-emphasis-style"]=
"filled circle",r["text-emphasis-color"]="currentcolor",r["webkit-text-emphasis"]="filled circle",H.textEmphasis){case 4:case 3:r["text-emphasis-position"]="under left";r["webkit-text-emphasis-position"]="under left";break;case 5:case 2:r["text-emphasis-position"]="over right",r["webkit-text-emphasis-position"]="over right"}return r},Pw0=function(K,H){if(K.pK&&H.length===0)return 0;
K=1;for(let r=0;r<H.length;r++){let O=H[r];typeof O.text==="string"&&(K+=O.text.split("\n").length-1,O.append||r===0||K++)}return K},FV=function(K){K=K.split("px");
return K.length>0?(K=Number(K[0]))?K:0:0},NPG=function(K,H,r){K.TF=K.TF||!!r;
var O={};Object.assign(O,K.K.zZ);Object.assign(O,r||H.K);Object.assign(O,K.S6.zZ);K.Ay&&(O.backgroundOpacity=0);(r=!K.V)&&gd5(K);var A=K.wZ&&K.Pn&&g.mS(O,K.Pn)?K.wZ:LUY(K,O),k=typeof H.text==="string",b=k?H.text.split("\n"):[H.text];for(let y=0;y<b.length;y++){var D=y>0||!H.append;let B=b[y];D&&!r?(gd5(K),A=LUY(K,O)):D&&r&&(r=!1);B&&(A.appendChild(k?g.bn(B):B),k||B.tagName!=="RUBY"||B.childElementCount!==4||g.z0||!g.ln(B.children[2],"text-emphasis")||(D=K.N?"padding-right":"padding-top",g.ln(B.children[2],
"text-emphasis-position")&&(D=K.N?"padding-left":"padding-bottom"),g.K3?g.Ut(A,D,"1em"):g.Ut(A,D,"0.5em")))}K.Pn=O;K.wZ=A;K.G.push(H)},gd5=function(K){if(K.V){var H=K.V;
if(K.hy){var r=K.K.textAlign;r===0?(H=H.firstElementChild)&&g.Ut(H,{"border-bottom-left-radius":"0"}):r===1&&(H=H.lastElementChild)&&g.Ut(H,{"border-bottom-right-radius":"0"})}}K.V=g.ka("SPAN");g.Ut(K.V,{display:"block"});g.DB(K.V,"caption-visual-line");K.B.appendChild(K.V)},LUY=function(K,H){var r=g.ka("SPAN");
g.Ut(r,{display:"inline-block","white-space":"pre-wrap"});g.Ut(r,xmG(K,H));r.classList.add("ytp-caption-segment");K.V.appendChild(r);K.hy&&K.B.children.length>1&&(K=K.K.textAlign,K===0?r.previousElementSibling||g.Ut(r,{"border-top-left-radius":"0"}):K===1&&g.Ut(r,{"border-top-right-radius":"0"}));r.previousElementSibling&&(g.Ut(r.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ut(r,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return r},
Um0=function(K,H,r){if(K===255&&H===255||!K&&!H)return{uo:K,
jX:H,result:0};K=Y$q[K];H=Y$q[H];if(K&128){var O;if(O=!(H&128))O=H,O=r.wV()&&r.jX===O;if(O)return{uo:K,jX:H,result:1}}else if(H&128&&1<=K&&K<=31)return{uo:K,jX:H,result:2};return{uo:K,jX:H,result:3}},VN4=function(K,H,r,O){H===255&&r===255||!H&&!r?(++K.B===45&&K.reset(),K.N.Y.clear(),K.V.Y.clear()):(K.B=0,S$L(K.N,H,r,O))},tNB=function(K,H){K.K.sort((r,O)=>{var A=r.time-O.time;
return A===0?r.order-O.order:A});
for(let r of K.K)K.time=r.time,r.type===0?VN4(K,r.Zp,r.Ut,H):r.type===1&&K.Y&496&&S$L(K.V,r.Zp,r.Ut,H);K.K.length=0},Cwo=function(K,H){switch(K){case 0:return l4B[(H&127)-32];
case 1:return WU4[H&15];case 2:return GiK[H&31];case 3:return ze0[H&31]}return 0},eQ=function(K,H){if(K.style.type===3){var r=0,O=0,A=K.V.time+0,k="",b="",D=A;
for(var y=1;y<=15;++y){var B=!1;for(var Z=O?O:1;Z<=32;++Z){var F=K.B[y][Z];if(F.K!==0){r===0&&(r=y,O=Z);B=String.fromCharCode(F.K);var X=F.timestamp;X<A&&(A=X);F.timestamp=D;b&&(k+=b,b="");k+=B;B=!0}if((F.K===0||Z===32)&&B){b="\n";break}else if(O&&!B)break}if(r&&!B)break}k&&H.N(r,O,A,D,k)}else for(O=r=0,k=A=K.V.time+0,b=1;b<=15;++b)for(D="",y=1;y<=32;++y)if(Z=K.B[b][y],F=Z.K,F!==0&&(r===0&&(r=b,O=y),B=String.fromCharCode(F),X=Z.timestamp,X<=A&&(A=X),D+=B,Z.reset()),y===32||F===0)D&&H.N(r,O,A,k,D),
A=k,D="",O=r=0},oK=function(K){return K.B[K.row][K.Y]},XV=function(K,H,r){H>=2&&K.Y>1&&(--K.Y,oK(K).K=0);
var O=oK(K);O.timestamp=K.V.time+0;O.K=Cwo(H,r);K.Y<32&&K.Y++},JdL=function(K,H,r,O){for(let A=0;A<O;A++)for(let k=0;k<=32;k++)K.B[H+A][k].copy(K.B[r+A][k])},wy=function(K,H,r){for(let O=0;O<r;O++)for(let A=0;A<=32;A++)K.B[H+O][A].reset()},dy=function(K){K.row=K.K>0?K.K:1;
K.Y=1;wy(K,0,15)},sdx=function(K){K.style.set(1);
K.K=K.N;K.K.K=0;K.K.style=K.style;K.B.mode=1<<K.K.N},cJ=function(K,H,r){var O=K.Y,A=!1;
switch(K.style.get()){case 4:case 1:case 2:K.style.get()===4&&O.K>0||(eQ(O,r),dy(K.Y),dy(K.N),O.row=15,O.K=H,A=!0)}K.style.set(3);K.K=O;K.K.style=K.style;K.B.mode=1<<O.N;A?O.Y=1:O.K!==H&&(O.K>H?(eQ(O,r),wy(O,O.row-O.K,H)):O.row<H&&(H=O.K),O.K=H)},mmo=function(K){K.style.set(4);
K.K=K.text;K.K.style=K.style;K.B.mode=1<<K.K.N},S$L=function(K,H,r,O){K.Y.update();
H=Um0(H,r,K.Y);switch(H.result){case 0:return;case 1:case 2:return}var A=H.uo;H=H.jX;if(32<=A||!A)K.K.mode&K.K.Y&&(r=A,r&128&&(r=127),H&128&&(H=127),K=K.N.K,r&96&&XV(K,0,r),H&96&&XV(K,0,H),r!==0&&H!==0&&K.style.type===3&&eQ(K,O));else if(A&16)a:if(!K.Y.matches(A,H)&&(r=K.Y,r.uo=A,r.jX=H,r.state=2,r=A&8?K.W:K.B,K.N=r,K.K.mode=1<<(K.V<<2)+(r.V<<1)+(r.style.type===4?1:0),(K.K.mode|1<<(K.V<<2)+(r.V<<1)+(r.style.type!==4?1:0))&K.K.Y))if(H&64){O=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(A&7)<<1|H>>5&1];
K=H&16?((H&14)>>1)*4:0;H=r.K;switch(r.style.get()){case 4:O=H.row;break;case 3:if(O!==H.row){if(O<H.K&&(O=H.K,O===H.row))break;var k=1+H.row-H.K;let b=1+O-H.K;JdL(H,b,k,H.K);r=k;A=H.K;b<k?(k=b+A-k,k>0&&(r+=k,A-=k)):(k=k+A-b,k>0&&(A-=k));wy(H,r,A)}}H.row=O;H.Y=K+1}else switch(A&7){case 1:switch(H&112){case 32:XV(r.K,0,32);break a;case 48:H===57?(O=r.K,oK(O).K=0,O.Y<32&&O.Y++):XV(r.K,1,H&15)}break;case 2:H&32&&XV(r.K,2,H&31);break;case 3:H&32&&XV(r.K,3,H&31);break;case 4:case 5:if(32<=H&&H<=47)switch(H){case 32:sdx(r);
break;case 33:O=r.K;O.Y>1&&(--O.Y,oK(O).K=0);break;case 36:O=r.K;K=oK(O);for(H=0;H<=15;H++)for(r=0;r<=32;r++)if(O.B[H][r]===K){for(;r<=32;r++)O.B[H][r].reset();break}break;case 37:cJ(r,2,O);break;case 38:cJ(r,3,O);break;case 39:cJ(r,4,O);break;case 40:XV(r.K,0,32);break;case 41:O=r;O.style.set(2);O.K=O.Y;O.K.K=0;O.K.style=O.style;O.B.mode=1<<O.K.N;break;case 42:O=r;K=O.text;K.K=15;K.style.set(4);dy(K);mmo(O);break;case 43:mmo(r);break;case 44:K=r;H=K.Y;switch(K.style.get()){case 1:case 2:case 3:eQ(H,
O)}wy(H,0,15);break;case 45:b:{H=r;K=H.K;switch(H.style.get()){default:case 2:case 1:break b;case 4:if(K.row<15){++K.row;K.Y=1;break b}break;case 3:}K.K<2&&(K.K=2,K.row<K.K&&(K.row=K.K));H=K.row-K.K+1;eQ(K,O);JdL(K,H,H+1,K.K-1);wy(K,K.row,1)}break;case 46:wy(r.N,0,15);break;case 47:K=r,eQ(K.Y,O),K.N.updateTime(K.B.time+0),O=K.N,K.N=K.Y,K.Y=O,sdx(K)}break;case 7:switch(H){case 33:case 34:case 35:O=r.K,(O.Y+=H&3)>32&&(O.Y=32)}}},f4G=function(K,H,r,O,A,k,b){var D=k[0],y=b[D.getAttribute("p")];
if(y.wi===1){var B=k[1],Z=k[2];k=k[3];D.getAttribute("t");B.getAttribute("t");Z.getAttribute("t");k.getAttribute("t");D.getAttribute("p");B.getAttribute("p");k.getAttribute("p");b=b[Z.getAttribute("p")];D=a4B(D.textContent,B.textContent,Z.textContent,k.textContent,b);return new TW(K,H,A,r,D,O,y)}switch(y.wi){case 9:case 10:y.textEmphasis=1;break;case 11:y.textEmphasis=2;break;case 12:y.textEmphasis=3;break;case 13:y.textEmphasis=4;break;case 14:y.textEmphasis=5}return new TW(K,H,A,r,D.textContent||
"",O,y)},a4B=function(K,H,r,O,A){var k=g.$g(),b=k?g.ka("DIV"):g.ka("RUBY"),D=g.ka("SPAN");
D.textContent=K;b.appendChild(D);K=k?g.ka("DIV"):g.ka("RP");K.textContent=H;b.appendChild(K);H=k?g.ka("DIV"):g.ka("RT");H.textContent=r;b.appendChild(H);r=A.wi;if(r===10||r===11||r===12||r===13||r===14)if(g.Ut(H,"text-emphasis-style","filled circle"),g.Ut(H,"text-emphasis-color","currentcolor"),g.Ut(H,"webkit-text-emphasis","filled circle"),A.wi===11||A.wi===13)g.Ut(H,"webkit-text-emphasis-position","under left"),g.Ut(H,"text-emphasis-position","under left");r=!0;if(A.wi===4||A.wi===7||A.wi===12||
A.wi===14)g.Ut(b,"ruby-position","over"),g.Ut(b,"-webkit-ruby-position","before");else if(A.wi===5||A.wi===6||A.wi===11||A.wi===13)g.Ut(b,"ruby-position","under"),g.Ut(b,"-webkit-ruby-position","after"),r=!1;A=k?g.ka("DIV"):g.ka("RP");A.textContent=O;b.appendChild(A);k&&(O=r,g.Ut(b,{display:"inline-block",position:"relative"}),k=b.firstElementChild.nextElementSibling,g.Ut(k,"display","none"),k=k.nextElementSibling,g.Ut(k,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ut(b.lastElementChild,"display","none"),O?(g.Ut(b,"padding-top","0.6em"),g.Ut(k,"top","0")):(g.Ut(b,"padding-bottom","0.6em"),g.Ut(k,"bottom","0")));return b},ndK=function(K){var H="_"+Qp++;
return new Es(0,0x8000000000000,0,H,K)},$Z=function(K,H){K=K.getAttribute(H);
if(K!=null)return Number(K)},xZ=function(K,H){K=K.getAttribute(H);
if(K!=null)return K==="1"},PJ=function(K,H){K=$Z(K,H);
return K!==void 0?K:null},LK=function(K,H){K=K.getAttribute(H);
if(K!=null)return gy.test(K),K},heq=function(K,H){var r={},O=H.getAttribute("ws");
Object.assign(r,O?K.C[O]:K.N);K=PJ(H,"mh");K!=null&&(r.kK=K);K=PJ(H,"ju");K!=null&&(r.textAlign=K);K=PJ(H,"pd");K!=null&&(r.M3=K);K=PJ(H,"sd");K!=null&&(r.yh=K);K=LK(H,"wfc");K!=null&&(r.windowColor=K);H=$Z(H,"wfo");H!==void 0&&(r.windowOpacity=H/255);return r},upG=function(K,H){var r={},O=H.getAttribute("wp");
O&&Object.assign(r,K.j[O]);K=PJ(H,"ap");K!=null&&(r.CZ=K);K=$Z(H,"cc");K!=null&&(r.Zv=K);K=$Z(H,"ah");K!=null&&(r.G2=K);K=$Z(H,"rc");K!=null&&(r.So=K);H=$Z(H,"av");H!=null&&(r.md=H);return r},q$G=function(K,H,r,O){var A={};
Object.assign(A,upG(K,H));Object.assign(A,heq(K,H));O?g.mS(A,K.N)?(O=K.V,A=K.N):O="_"+Qp++:O=H.getAttribute("id")||"_"+Qp++;K=$Z(H,"t")+r;H=$Z(H,"d")||0x8000000000000;if(A.M3===2||A.M3===3)r=A.So,A.So=A.Zv,A.Zv=r;return new Es(K,H,0,O,A)},NO=function(K){K=g.Pv(Math.round(K),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-K.length)+K},p$o=function(K,H,r,O,A){O===0&&(O=0x8000000000000);
var k={};H.wpWinPosId&&Object.assign(k,K.N.get(H.wpWinPosId));H.wsWinStyleId&&Object.assign(k,K.V.get(H.wsWinStyleId));K=H.rcRowCount;K!==void 0&&(k.So=K);H=H.ccColCount;H!==void 0&&(k.Zv=H);if(k.M3===2||k.M3===3)H=k.So,k.So=k.Zv,k.Zv=H;return new Es(r,O,0,A,k)},YZ=function(K){var H=K.byteOffset;
K.byteOffset+=1;return K.K.getUint8(H)},Us=function(K){var H=K.byteOffset;
K.byteOffset+=4;return K.K.getUint32(H)},K2o=function(K){if(typeof K==="string")return!1;
K=new ReL(K,0);return iSx(K)},iSx=function(K){if(!(K.byteOffset<K.K.byteLength)||Us(K)!==1380139777)return!1;
K.version=YZ(K);if(K.version>1)return!1;YZ(K);YZ(K);YZ(K);return!0},H7B=function(K,H){if(!H)return"";
K.N&&K.Y.params.yh!==1&&(H*=-1);return`translate${K.N?"X":"Y"}(${H}px)`},rjB=function(K){K.zF=Array.from(K.element.getElementsByClassName("caption-visual-line"));
for(var H=K.Y.params.So,r=0,O=0,A=K.zF.length-1;r<H&&A>-1;){var k=K.zF[A];O+=K.N?k.offsetWidth:k.offsetHeight;r++;A--}K.KK=O;H=Math;r=H.max;isNaN(K.iG)&&((O=K.K.Zv)?(A=g.ka("SPAN"),g.vQ(A,"\u2013".repeat(O)),g.Ut(A,xmG(K,K.K.zZ)),K.B.appendChild(A),K.iG=A.offsetWidth,K.B.removeChild(A)):K.iG=0);O=K.B;H=r.call(H,K.iG,K.d1,(K.N?O.offsetHeight:O.offsetWidth)+1);K.vn&&(H=Math.min(H,K.maxWidth));K.Bn=H},O7u=function(K,H){rjB(K);
var r=K.zF.reduce((O,A)=>(K.N?A.offsetWidth:A.offsetHeight)+O,0);
r=K.KK-r;if(r!==K.O5){let O=r>0&&K.O5===0,A=r<K.O5;H||isNaN(r)||O||!A||(g.DB(K.element,"ytp-rollup-mode"),K.Z(K.element,"transitionend",K.fK));g.Ut(K.B,"transform",H7B(K,r));K.O5=r}rjB(K)},kqK=function(K,H,r,O){var {formatId:A,
kv:k,startTimeMs:b,durationMs:D}=K.Ao(H),y={formatId:A,startTimeMs:b,durationMs:D,OM:k,CG:k},B=AjK(K.Zu,y.startTimeMs),Z=B>=0?K.Zu[B]:null,F=Z?Z.startTimeMs+Z.durationMs:0,X=y.startTimeMs+y.durationMs;!Z||y.startTimeMs-F>K.N?K.Zu.splice(B+1,0,y):(Z.durationMs=Math.max(F,X)-Z.startTimeMs,Z.CG=Math.max(Z.CG,y.CG));O(K.Zu);O=g.Kl(H);K=K.V;O=O.buffer.slice(O.byteOffset,O.byteLength+O.byteOffset);H=H.info.N;K.Bn?K.j==null?g.xe(K.logger,350058965,"Null loaded track meta data at captions data received"):
r.qp(O,K.j,H*1E3):g.xe(K.logger,350058965,"Null Representation at captions data received")},yjB=function(K,H){K.Y=(r,O)=>{if(K.D.X().experiments.cn("html5_sabr_live_support_subfragmented_captions"))(K.K?K.K=K.K.merge(r):(K.K=r,b74(K.K)),K.K)?r.info.WI&&(DR4(K.K),kqK(K,K.K,H,O),K.K=null):g.xe(K.logger,350058965,"Empty slice");
else if(r.info.WI){var A=r;if(K.zG.length>0){for(A=K.zG.shift();K.zG.length>0;)A=A?.merge(K.zG.shift());A=A?.merge(r)}A?(b74(A),DR4(A),kqK(K,A,H,O)):g.xe(K.logger,350058965,"Empty slice")}else K.zG.push(r)};
K.D.addEventListener("sabrCaptionsDataLoaded",K.Y)},AjK=function(K,H){K=g.eo(K,{startTimeMs:H},(r,O)=>r.startTimeMs-O.startTimeMs);
return K>=0?K:-K-2},b74=function(K){try{var H=g.Og(K)*1E3}catch(r){H=K.info.segmentStartTime*1E3}H<0&&(H=K.info.segmentStartTime*1E3);
K.info.segmentStartTime=H/1E3;K.info.N=H/1E3},DR4=function(K){try{var H=g.jA1(K)*1E3}catch(r){H=K.info.B*1E3}H<0&&(H=K.info.B*1E3);
K.info.B=H/1E3;K.info.G=H/1E3},j44=function(K,H){if(!g.lEm(K)||K.K!=null&&g.px(H,K.K)&&K.K.K.rawcc!=null)return!1;
H=!!K.K&&K.K.isManifestless&&Object.values(K.K.K).some(r=>g.R7(r,"386"));
K=!!K.K&&!K.K.isManifestless&&g.Wh5(K.K);return H||K},MZu=function(K,H,r){var O=[];
for(let A in K.Y.K){if(!K.Y.K.hasOwnProperty(A))continue;let k=K.Y.K[A];if(g.R7(k,r||null)){let b=k.info.captionTrack;b&&b.languageCode===H&&O.push(k)}}return O.length?O[0]:null},BX5=function(K,H){var r=[];
for(let A in K.Y.K){if(!K.Y.K.hasOwnProperty(A))continue;var O=K.Y.K[A];if(g.R7(O,H||null)){let k=O.info.id,b=k,D=`.${k}`,y="",B="";if(O=O.info.captionTrack)k=O.languageCode,b=O.displayName,D=O.vssId,y=O.kind,B=O.id;r.push(new g.jC({id:A,languageCode:k,languageName:b,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:D,kind:y,captionId:B}))}}return r},IMG=function(K){var H=vT4.length;
if(K.byteLength<H)return!1;K=new Uint8Array(K,0,H);for(let r=0;r<H;r++)if(vT4[r]!==K[r])return!1;return!0},SQ=function(K){K=K.split(":");
var H=0;for(let r of K)H=H*60+Number(r);return H*1E3},Z7o=function(K,H,r,O){O=Object.assign({kK:0},O);
return new Es(K,H,r,"_"+Qp++,O)},F24=function(K,H,r,O,A,k,b,D,y){switch(b.tagName){case "b":D.bold=!0;
break;case "i":D.italic=!0;break;case "u":D.underline=!0}for(let Z=0;Z<b.childNodes.length;Z++){var B=b.childNodes[Z];if(B.nodeType===3)B=new TW(H,r,O,A.id,B.nodeValue,k||Z>0,g.zL(D)?void 0:D),y.push(B),A.K.push(B);else{let F={};Object.assign(F,D);F24(K,H,r,O,A,!0,B,F,y)}}},oTB=function(K,H,r){if(typeof H==="string"||K2o(H))return[{trackData:H,
NA:r}];if(typeof H==="string"&&H.substring(0,6)==="WEBVTT"||typeof H!=="string"&&IMG(H))return[{trackData:H,NA:r}];var O=new DataView(H);if(O.byteLength<=8||O.getUint32(4)!==1718909296)return[];var A=g.eVt(O);if(K.U1&&A){var k=g.nL(A),b=g.hz(A);A=A.segmentNumber;k&&A&&K.U1.Rz(A,k,b)}K=g.Ay(O,1835295092);if(!K||!K.length||!K[0].size)return[];k=[];for(b=0;b<K.length;b++)A=K[b],A=new Uint8Array(H,A.dataOffset,A.size-(A.dataOffset-A.offset)),A=g.so(A),k.push({trackData:A,NA:r+b*1E3});ew5(O,k,r);return k=
k.filter(D=>!!D.trackData)},wV4=function(K,H,r){K.K||(K.K=new XVu);
K=K.K.B(H,r);Math.random()<.01&&g.WZ(Error("Deprecated subtitles format in web player: WebVTT"));return K},ew5=function(K,H,r){var O=g.i1(K,0,1836476516),A=9E4;
O&&(A=g.K2(O)||9E4);O=0;var k=g.Ay(K,1836019558);for(let D=0;D<k.length;D++){var b=k[D];D<H.length&&(b=g.i1(K,b.dataOffset,1953653094))&&(b=g.i1(K,b.dataOffset,1952867444))&&(b=g.Ow(b)/A*1E3,D===0&&(O=b),H[D].NA=b-O+r||r*D*1E3)}},dRB=function(K){var H={};
if(K=g.IQ(K))H.lang=K,g.Qop.test(K)&&(H.M3=1);return H},Vp=function(K){return K.B==="HLS"&&K.aE?!0:K.wZ&&K.aE&&K.B!=="LIVE"&&K.B!=="SABR_LIVE"},cj0=function(K){return!K.N&&K.wZ&&K.Ay&&(K.B==="LIVE"||K.B==="SABR_LIVE")},tX=function(K,H,r=!1){var O=K.Qg.O("enable_player_captions_new_style_defaults")?TXK:Q4Y,A=O.zZ;
K.V={};Object.assign(K.V,O);K.V.zZ={};Object.assign(K.V.zZ,A);K.W={zZ:{}};var k=H.backgroundOverride?K.W:K.V,b=H.background||A.background;gy.test(b);k.zZ.background=b;k=H.colorOverride?K.W:K.V;b=H.color||A.color;gy.test(b);k.zZ.color=b;k=H.windowColorOverride?K.W:K.V;b=H.windowColor||O.windowColor;gy.test(b);k.windowColor=b;k=H.backgroundOpacityOverride?K.W:K.V;b=H.backgroundOpacity;b==null&&(b=A.backgroundOpacity);k.zZ.backgroundOpacity=b;k=H.fontSizeIncrementOverride?K.W:K.V;b=H.fontSizeIncrement;
b==null&&(b=A.fontSizeIncrement);k.zZ.fontSizeIncrement=b;b=H.fontStyleOverride?K.W:K.V;k=H.fontStyle;k==null&&(k=A.bold&&A.italic?3:A.bold?1:A.italic?2:0);b=b.zZ;switch(k){case 1:b.bold=!0;delete b.italic;break;case 2:delete b.bold;b.italic=!0;break;case 3:b.bold=!0;b.italic=!0;break;default:delete b.bold,delete b.italic}k=H.textOpacityOverride?K.W:K.V;b=H.textOpacity;b==null&&(b=A.textOpacity);k.zZ.textOpacity=b;k=H.windowOpacityOverride?K.W:K.V;b=H.windowOpacity;b==null&&(b=O.windowOpacity);k.windowOpacity=
b;O=H.charEdgeStyleOverride?K.W:K.V;k=H.charEdgeStyle;k==null&&(k=A.charEdgeStyle);O.zZ.charEdgeStyle=k;O=H.fontFamilyOverride?K.W:K.V;k=H.fontFamily;k==null&&(k=A.fontFamily);O.zZ.fontFamily=k;K.loaded&&K.vn();r&&g.Zh("yt-player-caption-display-settings",H,2592E3)},lk=function(K,H,r){H&&!K.Ib?(H=ndK({M3:0,
lang:"en"}),K.Ib=[H,new TW(H.start,H.end-H.start,0,H.id,r??"Captions look like this")],K.player.No(K.Ib)):!H&&K.Ib&&(ETB(K,K.Ib),K.Ib=null)},xRS=function(K){if(K.Qg.O("enable_player_captions_persistence_state_machine")){var H=g.Fu("yt-player-caption-persistence");
if(H==null){let r=g.cN().s5(65);if(r===!0)H=!1;else{let O=g.SR(K.Qg)?WJ(K):$Rx(K);O!=null?H=!!O:r===!1&&(H=!0)}H!==void 0&&GW(K,H)}return H}},WJ=function(K){if(!K.D.isInline())return g.Fu("yt-player-sticky-caption")},$Rx=function(K){if(!K.storage)return null;
try{var H=K.storage.get("module-enabled")}catch(r){K.storage.remove("module-enabled")}return H},zW=function(K){if(K.Qg.O("enable_player_captions_persistence_state_machine"))return xRS(K);
var H=void 0,r=g.cN().s5(65);if(g.SR(K.Qg)&&r!=null){if(WJ(K)!=null)return!1;H=!r}return H},P25=function(K){if(K.Qg.Pq===1||K.videoData.ga===1||g.H6(K.videoData,"yt:cc")==="alwayson")return!0;
if(K.videoData.captionTracks.length)var H=K.getAudioTrack().Y;if(K.Qg.O("enable_player_captions_persistence_state_machine")){var r=xRS(K);if(r!==void 0)return!!r}else if(K.Qg.Pq===2&&(g.SR(K.Qg)?r=WJ(K):r=$Rx(K),r!=null))return!!r;r=vJ(K.player.getAudioTrack(),g.SR(K.Qg));var O=g.H6(K.videoData,"yt:cc");if(zW(K)===void 0){if(r==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return O?O==="on":!0;if(r==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return O==="on"}else return O==="on";return H==="ON"||g.H6(K.videoData,
"yt:cc")==="on"},CK=function(K,H=!1){if(K.Y&&!H||!K.videoData.captionTracks.length)return!1;
K=K.getAudioTrack();return!!K.K||K.Y==="FORCED_ON"},gTq=function(K,H){if(K.Y){var r=K.D.hq().zL().textTracks,O=null;
K.B==="HLS"?O=K.Y.getId():O=K.Y.toString();for(let k=0;k<r.length;k++){var A=r[k];A.id===O&&(H?A.mode!=="showing"&&(A.mode="showing",A=K.Y,K.Fq(A,!!A,JX(K)?"g":K.G?"m":"s")):A.mode==="showing"&&(A.mode="disabled"))}}},JX=function(K){var H=mR(K);
return!!H&&K.Y===H},L2K=function(K,H){if(K.B==="HLS")return!1;
g.v6(K.videoData)&&(H=!0);H||(H=K.B==="TTS"?!1:K.B==="INNERTUBE"?!1:!0);return H||K.Qg.O("web_watch_disable_account_level_captions_settings")&&g.SR(K.Qg)?!0:!!g.cN().s5(66)},mR=function(K){return K.C&&K.C.K},aK=function(K,H){if(!K.K)return null;
if(K.C&&K.C.N)return K.C.N;H=L2K(K,H);H=g.gM(K.K.K,H);var r=null;if(BPS(K.Qg)){var O=K.D.isInline()?void 0:g.Fu("yt-player-caption-sticky-language");var A=[O,K.videoData.captionsLanguagePreference,K.Qg.captionsLanguagePreference,g.H6(K.videoData,"yt:cc_default_lang")];let D=!1;for(let y=0;y<A.length;y++){let B=A[y];if(B){D=!0;for(var k=0;k<H.length;k++)if(g.IQ(H[k])===B)return H[k];for(k=0;k<H.length;k++)if(g.IQ(H[k]).split("-")[0]===B.split("-")[0])return H[k]}}if(D&&K.K&&(A=K.K.C,A.length))for(var b of A)if(b.languageCode===
O){r=b;break}}else for(b=[K.videoData.captionsLanguagePreference,K.Qg.captionsLanguagePreference,g.H6(K.videoData,"yt:cc_default_lang")],O=0;O<b.length;O++)for(A=0;A<H.length;A++)if(g.IQ(H[A])===b[O])return H[A];b=null;K.C&&K.C.B&&(b=K.C.B);b||(b=H.find(D=>D.isDefault)||null);
b||(b=H[0]||mR(K));b&&r&&g.IQ(b).split("-")[0]!==r.languageCode.split("-")[0]&&(b=MN4(b,r));return b},NXL=function(K,H){var r=g.gM(K.K.K,!0),O=[];
for(let A=0;A<r.length;A++){let k=r[A],b=g.ka("TRACK");b.setAttribute("kind","subtitles");b.setAttribute("label",g.BK(k));b.setAttribute("srclang",g.IQ(k));b.setAttribute("id",k.toString());K.KK||b.setAttribute("src",K.K.W(k,"vtt"));k===H&&b.setAttribute("default","1");O.push(b)}H=K.D.hq();H.Bn(O);O=H.zL();K.Ay&&K.zF.Z(O.textTracks,"change",K.CE)},uk=function(K,H,r){K.loaded&&K.unload();
r!=null&&(K.G=r,K.G&&(K.Qg.O("enable_player_captions_persistence_state_machine")?GW(K,!!H):g.SR(K.Qg)?fK(K,!!H):nK(K,!!H)));H!==null||CK(K,!0)||K.Fq(H,!!H,K.G?"m":"s");K.Y=H;CK(K)&&(K.Y=mR(K));hX(K,K.Y??void 0);K.load()},GW=function(K,H){K.Qg.O("enable_player_captions_persistence_state_machine")&&g.Zh("yt-player-caption-persistence",H,3122064E3)},fK=function(K,H){K.D.isInline()||g.Zh("yt-player-sticky-caption",H,2592E3)},nK=function(K,H){if(K.storage)try{K.storage.set("module-enabled",H)}catch(r){}},
hX=function(K,H){K.Qg.O("html5_modify_caption_vss_logging")&&(K.videoData.Yj=H)},UR4=function(K,H){var r=K.Nd[H.id];
r&&r.Y!==H&&(r.dispose(),delete K.Nd[H.id],r=null);r||(r=YLB(K,H))&&(K.Nd[H.id]=r)},SLB=function(K,H){var r=H.windowId;
K.hy[r]||(K.hy[r]=[]);K.hy[r].push(H)},YLB=function(K,H){var r=VZx(K);
if(!r)return null;var O=K.Y?g.IQ(K.Y):null;O&&g.Qop.test(O)&&(H.params.M3=1);var A=K.pK.getPlayerSize();O=A.height*K.Bn.height;A=A.width*K.Bn.width;K.Qg.playerStyle!=="google-live"||K.V.isDefault||Object.assign(H.params,K.V);switch(H.params.kK!=null?H.params.kK:H.K.length>1?1:0){case 1:return new tZK(H,K.V,K.W,r.width,r.height,A,O,K.Qg.experiments,K.ZE.bind(K),K.D);case 2:return new lMo(H,K.V,K.W,r.width,r.height,A,O,K.Qg.experiments,K.ZE.bind(K),K.D);default:return new qO(H,K.V,K.W,r.width,r.height,
A,O,K.Qg.experiments,K.ZE.bind(K),K.D)}},VZx=function(K){var H=K.pK.getVideoContentRect(!0).height,r=K.pK.getVideoContentRect(!0).width;
if(!H||!r)return null;H*=K.Bn.height;r*=K.Bn.width;return{width:r,height:H}},ETB=function(K,H){K.player.T4(H);
for(let r of H)g.b0(K.iG,r);BJ(K.TF)},W2Q=function(K,H){if(!K.K)return{};
if(H){g.zL(H)||K.mK(H.vss_id,"m");if(K.N&&K.B!=="HLS"||!g.Qn(H))return;if(g.zL(H)){uk(K,null,!0);return}let O;var r=g.gM(K.K.K,!0);for(let A=0;A<r.length;A++){let k=r[A];k.languageCode!==H.languageCode||O&&(k.languageName!==H.languageName||(k.captionId||"")!==(H.captionId||"")||g.BK(k)!==H.displayName)||(O=H.translationLanguage?MN4(k,H.translationLanguage):k)}K.W0(H.position);!O||O===K.Y&&K.loaded||(H=g.Ob(),r=g.IQ(O),H.length&&r===H[H.length-1]||(H.push(r),g.Zh("yt-player-caption-language-preferences",
H)),BPS(K.Qg)&&!K.D.isInline()&&g.Zh("yt-player-caption-sticky-language",r,2592E3),uk(K,O,!0))}else return K.loaded&&K.Y&&!JX(K)?g.vK(K.Y):{};return""};
g.i5.prototype.Rz=g.AH(67,function(K,H,r){this.Y.set(K,{Rd:H,XL:r})});
g.KT.prototype.Rz=g.AH(66,function(K,H,r){this.Bn.Rz(K,H,r)});
g.G2.prototype.KK=g.AH(65,function(){return!1});
g.G2.prototype.N=g.AH(64,function(){});
g.z2.prototype.N=g.AH(63,function(K,H,r){this.Md();H=this.W(K,H);var O=this.lG.X().O("html5_report_captions_ctmp_qoe"),A=(0,g.f)();this.B();jd0(this,H,{format:"RAW",onSuccess:k=>{this.Y=null;if(O){var b=(k.responseText.length/1024).toFixed();let D=(0,g.f)();this.videoData.Yv("capresp",{ms:D-A,kb:b})}b=k.getResponseHeader&&k.getResponseHeader("Content-Length")?Number(k.getResponseHeader("Content-Length")):0;r.qp(k.responseText,K,void 0,void 0,b)},
onError:O?k=>{this.videoData.Yv("capfail",{status:k?.status??0})}:void 0,
withCredentials:!0})});
g.CE.prototype.N=g.AH(62,function(K,H,r){this.Md();H=this.W(K,H);this.B();this.Y=g.At(H,{format:"RAW",onSuccess:O=>{this.Y=null;var A=O.getResponseHeader&&O.getResponseHeader("Content-Length")?Number(O.getResponseHeader("Content-Length")):0;r.qp(O.responseText,K,void 0,void 0,A)},
withCredentials:!0})});
g.My.prototype.j=g.AH(61,function(){this.mediaElement.j()});
g.bs.prototype.j=g.AH(60,function(){var K=g.aw(document,"track",void 0,this.K);for(let H=0;H<K.length;H++)g.Mu(K[H])});
g.My.prototype.O5=g.AH(59,function(){return this.mediaElement.O5()});
g.bs.prototype.O5=g.AH(58,function(){return!(!this.K.textTracks||!this.K.textTracks.addEventListener)});
g.My.prototype.Pn=g.AH(57,function(){return this.mediaElement.Pn()});
g.bs.prototype.Pn=g.AH(56,function(){return!!this.K.textTracks});
g.My.prototype.Bn=g.AH(55,function(K){this.mediaElement.Bn(K)});
g.bs.prototype.Bn=g.AH(54,function(K){for(let H=0;H<K.length;H++)this.K.appendChild(K[H])});
g.IB.prototype.mK=g.AH(40,function(K,H){this.app.bG().mK(K,H)});
g.VK.prototype.mK=g.AH(39,function(K,H){this.A.mK(K,H)});
g.Nr.prototype.mK=g.AH(38,function(K,H){K=[K,H];g.JK(this,g.fp(this.provider),"cfi",K)});
g.Ui.prototype.mK=g.AH(37,function(K,H){this.qoe&&this.qoe.mK(K,H)});
g.Cw.prototype.mK=g.AH(36,function(K,H){this.xS.mK(K,H)});
g.u5.prototype.mK=g.AH(35,function(){});
g.SJ.prototype.mK=g.AH(34,function(K,H){g.M$(this,37,[K,H])});
g.IB.prototype.Fq=g.AH(33,function(K,H,r){this.app.bG().Fq(K,H,r)});
g.VK.prototype.Fq=g.AH(32,function(K,H,r){this.A.Fq(K,H,r)});
g.Nr.prototype.Fq=g.AH(31,function(K,H,r){if(this.wZ!==K||this.aE!==H)H=H==="rawcc"?"":H,r=[K,H,this.wZ,r],g.JK(this,g.fp(this.provider),"cfs",r),this.wZ=K,this.aE=H});
g.Ui.prototype.Fq=g.AH(30,function(K,H,r){this.qoe&&this.qoe.Fq(K,H,r)});
g.Cw.prototype.Fq=g.AH(29,function(K,H,r){this.xS.Fq(K,H,r)});
g.u5.prototype.Fq=g.AH(28,function(){});
g.SJ.prototype.Fq=g.AH(27,function(K,H,r){g.M$(this,36,[K,H,r])});
g.RJ.prototype.Ko=g.AH(9,function(K){return(K=this.B(K))?K.K:0});
g.He.prototype.Ko=g.AH(8,function(){return 0});
var FUB=/#(.)(.)(.)/,ZSL=/^#(?:[0-9a-f]{3}){1,2}$/i,GqK={en:"English"},zwK=class extends g.G2{constructor(K){super(K);this.Y=new Set}V(K){var H=this.lG.hq();if(H&&H.zL()){H=H.zL().textTracks;for(let r of H)r.kind==="subtitles"&&!this.Y.has(r.language)&&r.language&&(g.qw(this.K,new g.jC({languageCode:r.language,languageName:r.language,kind:r.kind,id:r.id,displayName:GqK[r.label]||r.label,vss_id:`.${r.language}`})),this.Y.add(r.language))}g.gM(this.K).length>0&&K.fL()}},C2u=class{constructor(){this.segments=
[]}contains(K){K=g.eo(this.segments,K);return K>=0||K<0&&(-K-1)%2===1}length(){return this.segments.length/2}},JjG=class extends g.Le{constructor(K,H,r,O,A,k){super();this.policy=K;this.player=H;this.LK=r;this.j=O;this.V=A;this.KK=k;this.N=new C2u;this.W=-1;this.Y=this.B=this.K=null;this.Bn=0;this.G=new g.Ko(this.Ib,1E3,this);this.events=new g.Zc(this);g.W(this,this.G);g.W(this,this.events);this.events.Z(H,"SEEK_COMPLETE",this.C);this.C();this.Ib()}Vg(){super.Vg();this.Y&&this.Y.cancel()}C(){this.seekTo(this.player.getCurrentTime())}seekTo(K){K-=
this.player.Se();var H=this.K;this.K=g.JH(this.LK.G(K).E5);H!==this.K&&this.KK&&this.KK()}reset(){this.N=new C2u;this.W=-1;this.Y&&(this.Y.cancel(),this.Y=null)}Ib(){this.Md();var K;if(K=this.K!=null)K=this.K,K=K.LK.N(K);if(K&&!this.Y&&!(this.K&&this.K.segmentStartTime-this.player.getCurrentTime()>30)){K=this.K;K=K.LK.wZ(K);let A=K.E5[0];if(this.player.getVideoData().enableServerStitchedDai){var H=this.player.t6();if(H){var r=A.LK.info.id;let k=A.kv;var O=K.E5[0].N;if(this.policy.TF){if(H=g.Fpd(H,
O,k,r,3))K.N=H}else if(r=H.n7(O,k,r,3))if(O=2,H.UK.has(k)?O=0:g.YV(H,k)&&(O=1),H=O,H===0)r&&(K.K=new g.yS(r));else if(H===2){this.G.start();X$G(this)&&this.seekTo(this.player.getCurrentTime());return}}}A.LK.index.Kh(A.kv)?(this.N.contains(K.E5[0].kv)||w$L(this,K),this.K=g.JH(K.E5)):X$G(this)&&this.seekTo(this.player.getCurrentTime())}this.G.start()}},s45=class extends g.G2{constructor(K,H){super(H);this.Y=K;this.D=H;this.j=null;this.Ib=!1;this.logger=new g.$e("caps");this.Bn=g.px(this.D,this.Y)}N(K,
H,r){this.B();H=dmL(this,K.getId());H||(H=K.languageCode,H=this.Y.isManifestless?cd0(this,H,"386"):cd0(this,H));if(H){var O=(H.index.Ko(H.index.ff())-H.index.getStartTime(H.index.ff()))*1E3,A=new g.rGN(this.D.X());this.j=new JjG(A,this.D,H,(k,b)=>{r.qp(k,K,b,O)},this.Bn||g.at(H.info),()=>{this.j&&this.j.reset();
this.Ib=!0})}}KK(){var K=this.Ib;
this.Ib=!1;return K}V(K){var H=this.D.X().O("html5_fallback_if_rawcc_missing");var r=this.Y.K.rawcc!=null;if(!this.Bn||!r&&H)H=this.Y.isManifestless?TPo(this,"386"):TPo(this);else{if(!r){g.xe(this.logger,386248249,"rawcc used but unavailable");return}H=[new g.jC({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.jC({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let O of H)g.qw(this.K,
O);K.fL()}B(){this.j&&(this.j.dispose(),this.j=null)}W(){return""}},gy=/^#(?:[0-9a-f]{3}){1,2}$/i;var mRY=["left","right","center","justify"];var TW=class extends g.bZ{constructor(K,H,r,O,A,k=!1,b=null){super(K,K+H,{priority:r,namespace:"captions"});this.windowId=O;this.text=A;this.append=k;this.K=b}toString(){return super.toString()}};var qO=class extends g.R{constructor(K,H,r,O,A,k,b,D,y,B){var Z=B.isInline()&&!0,F={};Object.assign(F,H);Object.assign(F,K.params);Object.assign(F,r);var X={};Object.assign(X,H.zZ);K.params.zZ&&Object.assign(X,K.params.zZ);Object.assign(X,r.zZ);Z&&(X.background&&(F.windowColor=X.background),F.windowOpacity=.6,X.backgroundOpacity=0);F.zZ=X;var w=F.M3===1,T=[{L:"span",S:"captions-text",U:{style:"word-wrap: normal; display: block;"}}],S=D.cn("caption_edit_on_hover")&&B.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
S&&T.unshift({L:"button",S:"caption-edit",U:{tabindex:"0","aria-label":eeq()},J:[{L:"svg",U:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},J:[{L:"path",U:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({L:"div",S:"caption-window",U:{id:`caption-window-${K.id}`,dir:w?"rtl":"ltr",tabindex:"0",lang:F.lang},J:T});this.experiments=
D;this.G=[];this.TF=!1;this.Y=K;this.Pn=this.wZ=null;this.QS=k;this.Tq=b;this.V=null;this.maxWidth=k*.96;this.maxHeight=b*.96;this.K=F;this.S6=r;this.Nd=H;this.B=this.Rb("captions-text");K=this.B.style;this.hy=D.cn("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in K||"WebkitBoxDecorationBreak"in K);this.Jy=QdS(O,A,k,b);this.HD=y;S&&(this.W=this.Rb("caption-edit"),this.Z(this.W,"click",()=>{this.HD()}));
this.type=0;this.ZE=this.Jy*Edx(X);this.Ay=Z;this.pK=D.cn("enable_centered_caption_for_tvfilm_video")&&B.getVideoData().isTvfilmVideo;this.C=B.X().Sk().K.s5(g.GbH);this.vn=B.X().Sk().K.s5(g.zEm);O=new g.YF(this.element,!0);g.W(this,O);O.subscribe("dragstart",this.KB,this);O.subscribe("dragmove",this.ug,this);O.subscribe("dragend",this.lg,this);this.V6=this.aE=this.Pl=this.Wl=0;O="";this.K.windowOpacity&&(O=IK(this.K.windowColor),O="rgba("+O[0]+","+O[1]+","+O[2]+","+this.K.windowOpacity+")");A={"background-color":O,
display:this.K.isVisible===!1?"none":"","text-align":mRY[this.K.textAlign]};this.hy&&(A["border-radius"]=O?`${this.ZE*.25}px`:"");(this.N=this.Y.params.M3===2||this.Y.params.M3===3)&&$mu(this,this.element);g.Ut(this.element,A);Z&&this.element.parentElement?.style.setProperty("--caption-window-color",O);switch(this.K.CZ){case 0:case 1:case 2:g.DB(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.DB(this.element,"ytp-caption-window-bottom")}}KB(K,H){this.aE=K;this.V6=H;var r=g.hT(this.element,
this.element.parentElement);this.Wl=K-r.x;this.Pl=H-r.y}ug(K,H){if(K!==this.aE||H!==this.V6){g.bd(this.element,"ytp-dragging")||g.DB(this.element,"ytp-dragging");var r=g.p3(this.element);K=K-this.Wl-.02*this.QS;var O=H-this.Pl-.02*this.Tq,A=(K+r.width/2)/this.maxWidth*3;A=Math.floor(g.Pv(A,0,2));var k=(O+r.height/2)/this.maxHeight*3;k=Math.floor(g.Pv(k,0,2));H=A+k*3;K=(K+A/2*r.width)/this.maxWidth;K=g.Pv(K,0,1)*100;r=(O+k/2*r.height)/this.maxHeight;r=g.Pv(r,0,1)*100;this.Y.params.CZ=H;this.Y.params.md=
r;this.Y.params.G2=K;this.Y.params.isDefault=!1;this.K.CZ=H;this.K.md=r;this.K.G2=K;this.K.isDefault=!1;this.Nd.CZ=H;this.Nd.md=r;this.Nd.G2=K;this.Nd.isDefault=!1;this.pE()}}lg(){g.j5(this.element,"ytp-dragging")}pE(){this.j(this.G)}j(K){var H=this.Ay?0:Math.min(this.kS(),this.maxWidth),r=this.XH(),O=this.Ay;if(O){var A=getComputedStyle(this.B.parentNode);A=FV(A.borderLeftWidth)+FV(A.borderRightWidth)+FV(A.paddingLeft)+FV(A.paddingRight)}else A=0;var k="";this.Y.params.M3===3&&(k="rotate(180deg)");
var b=O?`calc(96% - ${A}px)`:"96%";g.Ut(this.element,{top:0,left:0,right:"",bottom:"",width:H?`${H}px`:"",height:r?`${r}px`:"","max-width":b,"max-height":b,margin:"",transform:""});this.jk(K);k={transform:k,top:"",left:"",width:H?`${H}px`:"",height:r?`${r}px`:"","max-width":"","max-height":""};b=this.K.CZ;var D=this.K.G2,y=this.K.md;this.pK&&b!=null&&(D=50,b=Math.floor(b/3)*3+1);D=D*.96+2;switch(b){case 0:case 3:case 6:(O=this.K.zZ.fontSizeIncrement)&&O>0&&this.K.M3!==2&&this.K.M3!==3&&(D=Math.max(D/
(1+O*2),2));k.left=`${D}%`;break;case 1:case 4:case 7:k.left=`${D}%`;let B=0;this.C||(B=this.B.offsetWidth);H||B?(H=H||B+1,k.width=`${H}px`,k["margin-left"]=O?`${H/-2-A/2}px`:`${H/-2}px`):(this.C&&(k.width="max-content"),k.transform+=" translateX(-50%)");break;case 2:case 5:case 8:k.right=`${100-D}%`}O=y*.96+2;switch(b){case 0:case 1:case 2:k.top=`${O}%`;break;case 3:case 4:case 5:k.top=`${O}%`;O=0;this.C||(O=this.element.clientHeight);(r=r||O)?(k.height=`${r}px`,k["margin-top"]=`${r/-2}px`):k.transform+=
" translateY(-50%)";break;case 6:case 7:case 8:k.bottom=`${100-O}%`}if(this.vn){switch(b){case 0:case 3:case 6:r=Math.max(0,100-2*D);break;case 2:case 5:case 8:r=Math.max(0,100-2*(100-D));break;default:r=Math.max(0,2*Math.min(D-2,98-D))}k["max-width"]=A>0?`calc(${r}% - ${A}px)`:`${r}%`}g.Ut(this.element,k);this.W&&(this.C?r=this.ZE:(K=Pw0(this,K),r=this.pK?K>0?this.B.offsetHeight/K:0:this.B.offsetHeight/K),this.W.style.height=`${r}px`,this.W.style.width=`${r}px`,this.element.style.paddingLeft=`${r+
5}px`,this.element.style.paddingRight=`${r+5}px`,this.C||(K=Number(this.element.style.marginLeft.replace("px",""))-r-5,r=Number(this.element.style.marginRight.replace("px",""))-r-5,this.element.style.marginLeft=`${K}px`,this.element.style.marginRight=`${r}px`))}jk(K){if(this.type===0&&this.Y.params.So!==void 0&&this.experiments.cn("web_enable_popon_asr_captions")){var H=K,r=this.Y.params.So;if(H.length===0||r<=0)K=[];else{K=[];for(let A=H.length-1;A>=0;A--){var O=H[A];K.unshift(O);let k=Pw0(this,
K);if(k>r){K.shift();typeof O.text==="string"&&(H=O.text.split("\n"),r=k-r,H.length-r>0&&(r=H.slice(r),O=new TW(O.start,O.end-O.start,O.priority||0,O.windowId,r.join("\n"),O.append,O.K),K.unshift(O)));break}}}}for(O=0;O<K.length&&K[O]===this.G[O];O++);if(this.TF||this.G.length>O)O=0,this.TF=!1,this.G=[],this.V=this.Pn=this.wZ=null,g.yz(this.B);for(;O<K.length;O++)NPG(this,K[O])}kS(){return 0}XH(){return 0}toString(){return super.toString()}};var fMu=class{constructor(){this.B=this.time=this.mode=this.Y=0;this.N=new aMo(this);this.V=new aMo(this);this.K=[];this.clear()}clear(){this.B=this.time=this.mode=0;this.K=[];this.reset()}reset(){this.mode=0;this.N.reset(0);this.V.reset(1)}},Y$q=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],nTQ=class{constructor(){this.type=0}set(K){this.type=K}get(){return this.type}},hwQ=class{constructor(){this.state=this.jX=this.uo=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}wV(){return this.state!==0}matches(K,H){return this.wV()&&K===this.uo&&H===this.jX}},uJY=class{constructor(){this.timestamp=this.K=0}copy(K){this.K=K.K;
this.timestamp=K.timestamp}reset(){this.timestamp=this.K=0}},pK=class{constructor(K){this.V=K;this.B=[];this.K=this.Y=this.row=0;this.style=new nTQ;this.N=0;for(K=0;K<=15;K++){this.B[K]=[];for(let H=0;H<=32;H++)this.B[K][H]=new uJY}}updateTime(K){for(let H=1;H<=15;++H)for(let r=1;r<=32;++r)this.B[H][r].timestamp=K}debugString(){var K="\n";for(let H=1;H<=15;++H){for(let r=1;r<=32;++r){let O=this.B[H][r];K=O.K===0?K+"_":K+String.fromCharCode(O.K)}K+="\n"}return K}reset(K){for(let H=0;H<=15;H++)for(let r=
0;r<=32;r++)this.B[H][r].reset();this.N=K;this.K=0;this.Y=this.row=1}},l4B=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],WU4=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],GiK=[193,201,211,218,220,252,8216,
161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],ze0=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],qLQ=class{constructor(K){this.B=K;this.V=0;this.style=new nTQ;this.W=new pK(this.B);this.G=new pK(this.B);this.text=new pK(this.B);this.Y=this.W;this.N=this.G;this.K=this.Y}reset(K,H){this.V=H;this.style.set(2);this.Y=this.W;this.N=this.G;this.K=this.Y;var r=(K<<
2)+(H<<1);this.W.reset(r);this.G.reset(r);this.text.reset((K<<2)+(H<<1)+1)}},aMo=class{constructor(K){this.K=K;this.V=0;this.B=new qLQ(this.K);this.W=new qLQ(this.K);this.Y=new hwQ;this.N=this.B}reset(K){this.V=K;this.Y.clear();this.N=this.B;this.B.reset(K,0);this.W.reset(K,1)}};var pVK=class{N(){}};var RK=class extends g.Le{reset(){}};var Es=class extends g.bZ{constructor(K,H,r,O,A){super(K,K+H,{priority:r,namespace:"captions"});this.id=O;this.params=A;this.K=[]}toString(){return super.toString()}},Qp=0;var Rw4=class extends RK{constructor(K){super();this.N=K;this.pens={};this.j={};this.C={};this.V="_"+Qp++;this.G={};this.Y=this.K=null;this.W=!0}reset(){this.G={};this.Y=this.K=null;this.W=!0}B(K,H){K=K.firstChild;K.getAttribute("format");H=H||0;Number.isFinite(H);K=Array.from(K.childNodes);for(var r of K)if(r.nodeType===1)switch(r.tagName){case "head":var O=r;break;case "body":var A=r}if(O){O=Array.from(O.childNodes);for(var k of O)if(k.nodeType===1)switch(k.tagName){case "pen":r=k.getAttribute("id");
O=this.pens;K={};var b=k.getAttribute("p");b&&Object.assign(K,this.pens[b]);b=xZ(k,"b");b!=null&&(K.bold=b);b=xZ(k,"i");b!=null&&(K.italic=b);b=xZ(k,"u");b!=null&&(K.underline=b);b=PJ(k,"et");b!=null&&(K.charEdgeStyle=b);b=PJ(k,"of");b!=null&&(K.offset=b);b=LK(k,"bc");b!=null&&(K.background=b);b=LK(k,"ec");b!=null&&(K.uK=b);b=LK(k,"fc");b!=null&&(K.color=b);b=PJ(k,"fs");b!=null&&b!==0&&(K.fontFamily=b);b=$Z(k,"sz");b!==void 0&&(K.fontSizeIncrement=b/100-1);b=$Z(k,"bo");b!==void 0&&(K.backgroundOpacity=
b/255);b=$Z(k,"fo");b!==void 0&&(K.textOpacity=b/255);b=PJ(k,"rb");b!=null&&b!==10&&b!==0&&(K.wi=b>10?b-1:b);b=PJ(k,"hg");b!=null&&(K.Mu=b);O[r]=K;break;case "ws":O=k.getAttribute("id");this.C[O]=heq(this,k);break;case "wp":O=k.getAttribute("id"),this.j[O]=upG(this,k)}}if(A){k=[];A=Array.from(A.childNodes);for(S of A)if(S.nodeType===1)switch(S.tagName){case "w":this.K=q$G(this,S,H,!1);(A=this.G[this.K.id])&&A.end>this.K.start&&(A.end=this.K.start);this.G[this.K.id]=this.K;k.push(this.K);break;case "p":var D=
S;K=H;A=[];O=D.getAttribute("w")||this.V;r=!!xZ(D,"a");K=($Z(D,"t")||0)+K;b=$Z(D,"d")||5E3;r||(!this.W&&this.Y&&this.Y.windowId===O&&this.Y.end>K&&(this.Y.end=K),this.Y&&this.Y.text==="\n"&&(this.Y.text=""));let G=r?6:5;var y=D.getAttribute("p");y=y?this.pens[y]:null;let z=Array.from(D.childNodes);z.length&&(this.W=D.getAttribute("d")!=null);for(D=0;D<z.length;D++){var B=z[D],Z=void 0;D>0&&(r=!0);let m;B.nodeType===1&&(m=B);if(m&&m.tagName==="s"){if((B=(B=m.getAttribute("p"))?this.pens[B]:null)&&
B.wi&&(B.wi===1?(B=z.slice(D,D+4),B.length===4&&(Z=f4G(K,b,O,r,G,B,this.pens),D+=3)):Z=f4G(K,b,O,r,G,[m],this.pens)),!Z){var F=m;Z=K;B=b;var X=O,w=r;let a=F.textContent?F.textContent:"";var T=F.getAttribute("p");T=T?this.pens[T]:null;F=$Z(F,"t")||0;Z=new TW(Z+F,B-F,G,X,a,w,T)}}else Z=new TW(K,b,G,O,B.textContent||"",r,y);A.push(Z);this.Y=Z}if(A.length>0){A[0].windowId===this.V&&(this.K=q$G(this,S,H,!0),k.push(this.K));for(let m of A)m.windowId=this.K.id,this.K.K.push(m),k.push(m)}}var S=k}else S=
[];return S}};var i7q=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),KZQ=class extends RK{constructor(K){super();this.W=K;this.K=new Map;this.N=new Map;this.V=new Map;this.Y=new Map}reset(){this.Y.clear()}B(K,H){K=JSON.parse(K);if(!K)return[];if(K.pens){var r=K.pens,O=0;for(var A of r){r={};var k=A.pParentId;k&&Object.assign(r,this.K.get(k));A.bAttr&&(r.bold=!0);A.iAttr&&(r.italic=!0);A.uAttr&&(r.underline=!0);k=A.ofOffset;k!=null&&(r.offset=k);A.szPenSize!==void 0&&(r.fontSizeIncrement=A.szPenSize/100-1);
k=A.etEdgeType;k!=null&&(r.charEdgeStyle=k);A.ecEdgeColor!==void 0&&(r.uK=NO(A.ecEdgeColor));k=A.fsFontStyle;k!=null&&k!==0&&(r.fontFamily=k);A.fcForeColor!==void 0&&(r.color=NO(A.fcForeColor));A.foForeAlpha!==void 0&&(r.textOpacity=A.foForeAlpha/255);A.bcBackColor!==void 0&&(r.background=NO(A.bcBackColor));A.boBackAlpha!==void 0&&(r.backgroundOpacity=A.boBackAlpha/255);(k=A.rbRuby)&&k!==10&&(r.wi=k>10?k-1:k,r.textEmphasis=i7q.get(r.wi));A.hgHorizGroup&&(r.Mu=A.hgHorizGroup);this.K.set(O++,r)}}if(K.wsWinStyles){O=
K.wsWinStyles;A=0;for(var b of O)O={},(r=b.wsParentId)?Object.assign(O,this.V.get(r)):Object.assign(O,this.W),b.mhModeHint!==void 0&&(O.kK=b.mhModeHint),b.juJustifCode!==void 0&&(O.textAlign=b.juJustifCode),b.pdPrintDir!==void 0&&(O.M3=b.pdPrintDir),b.sdScrollDir!==void 0&&(O.yh=b.sdScrollDir),b.wfcWinFillColor!==void 0&&(O.windowColor=NO(b.wfcWinFillColor)),b.wfoWinFillAlpha!==void 0&&(O.windowOpacity=b.wfoWinFillAlpha/255),this.V.set(A++,O)}if(K.wpWinPositions){A=K.wpWinPositions;b=0;for(var D of A)A=
{},(O=D.wpParentId)&&Object.assign(A,this.N.get(O)),D.ahHorPos!==void 0&&(A.G2=D.ahHorPos),D.apPoint!==void 0&&(A.CZ=D.apPoint),D.avVerPos!==void 0&&(A.md=D.avVerPos),D.ccCols!==void 0&&(A.Zv=D.ccCols),D.rcRows!==void 0&&(A.So=D.rcRows),this.N.set(b++,A)}if(K.events){K=K.events;D=[];for(let n of K)if(b=(n.tStartMs||0)+H,A=n.dDurationMs||0,n.id)O=String(n.id),K=p$o(this,n,b,A,O),D.push(K),this.Y.set(O,K);else{n.wWinId?O=n.wWinId.toString():(O="_"+Qp++,K=p$o(this,n,b,A,O),D.push(K),this.Y.set(O,K));
K=D;var y=n;A===0&&(A=5E3);r=this.Y.get(O);let r4=(k=!!y.aAppend)?6:5,Xd=y.segs,$N=null;y.pPenId&&($N=this.K.get(y.pPenId));for(y=0;y<Xd.length;y++){var B=Xd[y],Z=B.utf8;if(Z){var F=B.tOffsetMs||0;let xN=null;B.pPenId&&(xN=this.K.get(B.pPenId));if((r.params.kK!=null?r.params.kK:r.K.length>1?1:0)===2&&k&&Z==="\n")continue;B=null;var X=[],w;if(w=xN&&xN.wi===1)a:{w=Xd;var T=y;if(T+3>=w.length||!w[T+1].pPenId||!w[T+2].pPenId||!w[T+3].pPenId){w=!1;break a}var S=w[T+1].pPenId;(S=this.K.get(S))&&S.wi&&S.wi===
2?(S=w[T+2].pPenId,S=this.K.get(S),!S||!S.wi||S.wi<3?w=!1:(S=w[T+3].pPenId,w=(S=this.K.get(S))&&S.wi&&S.wi===2?!0:!1)):w=!1}if(w)F=Xd[y+1].utf8,B=Xd[y+3].utf8,w=Xd[y+2].utf8,T=this.K.get(Xd[y+2].pPenId),Z=a4B(Z,F,w,B,T),B=new TW(b,A,r4,O,Z,k,xN),y+=3;else{if(Z.indexOf("<")>-1){X=xN;w=$N;T=b;S=A;var G=F,z=r4,m=k;let m1=[];var a=g.C8(`<html>${Z}</html>`);if(!a.getElementsByTagName("parsererror").length&&a.firstChild?.childNodes.length)for(let pO of a.firstChild.childNodes){a=pO.textContent?.replace(/\n/g,
"")??"";if(pO.nodeType===3&&(!a||a.match(/^ *$/)!=null))continue;let kv={};Object.assign(kv,X||w);switch(pO?.tagName){case "b":kv.bold=!0;break;case "i":kv.italic=!0;break;case "u":kv.underline=!0}m1.push(new TW(T+G,S-G,z,r.id,a,m,kv))}X=m1}X.length||(X=[new TW(b+F,A-F,r4,r.id,Z,k,xN||$N)])}if(X.length)for(let m1 of X)K.push(m1),r.K.push(m1);else B&&(K.push(B),r.K.push(B))}k=!0}}H=D}else H=[];return H}};var HoS=class extends g.G2{constructor(K,H,r){super(K);this.videoData=H;this.audioTrack=r;this.C=H.ZF}N(K,H,r){I4S(this.videoData.videoId,K.vssId,r.qp)}V(K){if(this.audioTrack)for(let H of this.audioTrack.captionTracks)g.qw(this.K,H);K.fL()}};var tZK=class extends qO{constructor(K,H,r,O,A,k,b,D,y,B){super(K,H,r,O,A,k,b,D,y,B);this.type=1}jk(K){var H=this.Y.K;super.jk(K);for(K=K.length;K<H.length;K++){let A=H[K],k;if(O&&A.K===r)k=O;else{k={};Object.assign(k,A.K);Object.assign(k,rRx);var r=A.K;var O=k}NPG(this,A,k)}}},rRx={PR:!0};var ReL=class extends pVK{constructor(K,H){super();this.trackData=K;this.W=H;this.version=this.V=this.B=this.byteOffset=0;this.Y=[];this.K=new DataView(this.trackData)}N(K,H,r,O,A){if(r<O){let k="_"+Qp++;r=r/1E3-this.W;O=O/1E3-this.W;K=new Es(r,O-r,5,k,{textAlign:0,CZ:0,G2:H*2.5,md:K*5.33});A=new TW(r,O-r,5,k,A);this.Y.push(K);this.Y.push(A)}}},Ooq=class extends RK{constructor(K,H){super();this.Y=K;this.N=H;this.track=this.N.languageName==="CC3"?4:0;this.K=new fMu;this.K.Y=1<<this.track}B(K){K=new ReL(K,
this.Y);if(iSx(K)){for(;K.byteOffset<K.K.byteLength;)for(K.version===0?K.B=Us(K)*(1E3/45):K.version===1&&(K.B=Us(K)*4294967296+Us(K)),K.V=YZ(K);K.V>0;K.V--){var H=YZ(K);let r=YZ(K),O=YZ(K);H&4&&(H&3)===this.track&&(this.track===0||this.track===1)&&(H=this.K,H.K.push({time:K.B,type:this.track,Zp:r,Ut:O,order:H.K.length}))}tNB(this.K,K);return K.Y}return[]}reset(){this.K.clear()}};var lMo=class extends qO{constructor(K,H,r,O,A,k,b,D,y,B){super(K,H,r,O,A,k,b,D,y,B);this.type=2;this.zF=[];this.Bn=this.KK=this.O5=0;this.iG=NaN;this.d1=0;this.z5=null;this.E1=new g.Ko(this.fK,433,this);this.W&&(B.createClientVe(this.W,this,167342),this.Z(this.W,"click",()=>{B.logClick(this.W)}),K=new g.YF(this.element,!0),g.W(this,K),K.subscribe("hoverstart",()=>{B.logVisibility(this.W,!0)},this));
g.DB(this.element,"ytp-caption-window-rollup");g.W(this,this.E1);g.Ut(this.element,"overflow","hidden")}pE(){g.rb(this.E1)}fK(){this.element.removeEventListener("transitionend",this.fK,!1);g.j5(this.element,"ytp-rollup-mode");this.j(this.z5,!0)}XH(){return this.N?this.Bn:this.KK}kS(){return this.N?this.KK:this.Bn}j(K,H){this.z5=K;if(this.Y.params.So){var r=0;for(let O=0;O<this.G.length&&r<K.length;O++)this.G[O]===K[r]&&r++;r>0&&r<K.length&&(K=this.G.concat(K.slice(r)));this.d1=this.Bn;this.KK=this.Bn=
0;super.j(K);O7u(this,H)}super.j(K)}};var ARK=class{constructor(K,H,r,O){this.D=K;this.V=H;this.logger=r;this.Nv=O;this.Zu=[];this.K=null;this.B=[];this.zG=[];this.Y=null;this.b1={K$g:()=>this.Y,
VT:()=>this.Zu,
Vfy:A=>{this.B=A},
azb:()=>this.B};
K=this.D.X().experiments.K("html5_override_micro_discontinuities_threshold_ms");this.N=K>0?K:10}unload(){this.Y!=null&&(this.D.removeEventListener("sabrCaptionsDataLoaded",this.Y),this.Y=null);this.Zu=[];this.K=null;this.B=[];this.D.publish("sabrCaptionsBufferedRangesUpdated",this.Zu)}Ao(K){return{formatId:g.nt(K.info.LK.info,this.Nv),kv:K.info.kv+(this.Nv?0:1),startTimeMs:K.info.N*1E3,durationMs:K.info.G*1E3}}};var kax=class extends g.G2{constructor(K,H){super(H);this.Y=K;this.D=H;this.logger=new g.$e("caps");this.j=this.Bn=null;this.Ib=new ARK(this.D,this,this.logger,this.Y.Nv)}N(K,H,r){this.B();H=K.getId();H=H!=null&&H in this.Y.K?this.Y.K[H]:null;H||(H=K.languageCode,H=this.Y.isManifestless?MZu(this,H,"386"):MZu(this,H));H&&(this.j=K,this.Bn=H,yjB(this.Ib,r),this.D.publish("sabrCaptionsTrackChanged",g.nt(H.info,this.Y.Nv)))}V(K){var H=this.Y.isManifestless?BX5(this,"386"):BX5(this);for(let r of H)g.qw(this.K,
r);K.fL()}B(){this.j&&(this.j=this.Bn=null,this.Ib.unload(),this.D.publish("sabrCaptionsTrackChanged",null))}W(){return""}};var vT4="WEBVTT".split("").map(K=>K.charCodeAt(0)),XVu=class extends RK{constructor(){super()}B(K,H){K instanceof ArrayBuffer&&(K=g.so(new Uint8Array(K)));
var r=[];K=K.split(boL);for(let T=1;T<K.length;T++){var O=K[T],A=H;if(O!==""&&!Dqq.test(O)){var k=ik.exec(O);if(k&&k.length>=4){var b=SQ(k[1]),D=SQ(k[2])-b;b+=A;var y=(k=k[3])?k.split(" "):[];k={};var B=null;var Z="";var F=null,X="";for(let S of y){y=S.split(":");if(y.length!==2)continue;var w=y[1];switch(y[0]){case "line":y=w.split(",");y[0].endsWith("%")&&(B=y[0],k.md=Number.parseInt(B,10),y.length===2&&(Z=y[1].trim()));break;case "position":y=w.split(",");F=y[0];k.G2=Number.parseInt(F,10);y.length===
2&&(X=y[1].trim());break;case "align":switch(w){case "start":k.textAlign=0;break;case "middle":k.textAlign=2;break;case "end":k.textAlign=1}}}B||Z||(Z="end");if(!F)switch(k.textAlign){case 0:k.G2=0;break;case 1:k.G2=100;break;case 2:k.G2=50}if(k.textAlign!=null){B=0;switch(Z){case "center":B+=3;break;case "end":B+=6;break;default:B+=0}switch(X){case "line-left":B+=0;break;case "center":B+=1;break;case "line-right":B+=2;break;default:switch(k.textAlign){case 0:B+=0;break;case 2:B+=1;break;case 1:B+=
2}}Z=B<0||B>8?7:B;k.CZ=Z}O=O.substring(ik.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");X=k;k={};if(O.indexOf("<")<0&&O.indexOf("&")<0)A=Z7o(b,D,5,X),b=new TW(b,D,5,A.id,O,!1,g.zL(k)?void 0:k),r.push(A),r.push(b),A.K.push(b);else for(Z=O.split(yRu),Z.length===1?(O=5,X=Z7o(b,D,O,X)):(B=O=6,X=Object.assign({Zv:32},X),X=new Es(b,D,B,"_"+Qp++,X)),r.push(X),B=b,F=0;F<Z.length;F++)if(y=Z[F],F%2===0){w=g.C8(`<html>${y}</html>`);let S;w.getElementsByTagName("parsererror").length?(S=w.createElement("span"),
S.appendChild(w.createTextNode(y))):S=w.firstChild;F24(this,B,D-(B-b),O,X,F>0,S,k,r)}else B=SQ(y)+A}ik.lastIndex=0}}return r}},Dqq=/^NOTE/,boL=/(?:\r\n|\r|\n){2,}/,ik=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),yRu=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var jcx=class extends g.Le{constructor(K,H){super();this.D=K;this.Qg=H;this.K=null;this.U1=this.D.t6();this.logger=new g.$e("caps")}clear(){this.K&&this.K.dispose();this.K=null}reset(){this.K&&this.K.reset()}Vg(){super.Vg();this.clear()}};var Q4Y={windowColor:"#080808",windowOpacity:0,textAlign:2,CZ:7,G2:50,md:100,isDefault:!0,zZ:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},TXK={windowColor:"#080808",windowOpacity:0,textAlign:0,CZ:7,G2:50,md:100,isDefault:!0,zZ:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u4("captions",class extends g.We{constructor(K){super(K);this.D=K;this.iG=[];this.Nd={};this.hy={};this.G=!1;this.B="NONE";this.K=this.C=this.Ib=this.O5=this.Jy=null;this.fK={fL:()=>{this.fL()},
qp:(O,A,k,b,D=0)=>{var y=Number(this.videoData.X().Sk().K.s5(g.REH)??0);D>0&&y>0&&this.videoData.lengthSeconds>0&&D/this.videoData.lengthSeconds>y?this.D.Yv("tts",{dropcap:D}):this.qp(O,A,k,b)}};
this.Y=null;this.Qg=this.D.X();this.videoData=this.D.getVideoData();this.pK=this.D.uG();this.V={zZ:{}};this.W={zZ:{}};g.b2(this.videoData)?this.B="OFFLINE":g.KBp(this.videoData,this.D)?this.B="HLS":j44(this.videoData,this.D)?this.B="SABR_LIVE":g.Hwm(this.videoData,this.D)?this.B="LIVE":this.videoData.captionTracks.length?this.B="INNERTUBE":this.videoData.jk&&(this.B="TTS");this.wZ=this.Qg.controlsType==="3";this.jk=new jcx(this.D,this.Qg);this.zF=new g.Zc(this);this.j=new g.R({L:"div",S:"ytp-caption-window-container",
U:{id:"ytp-caption-window-container"}});this.Bn={top:0,right:0,bottom:0,left:0,width:1,height:1};var H=null,r=g.Co("yt-html5-player-modules::subtitlesModuleData");r&&(H=new g.YM(r));this.storage=H;H=K.hq();this.aE=!!H?.Pn();this.Ay=!!H?.O5();this.N=Vp(this);this.KK=cj0(this);g.W(this,this.jk);this.N?this.Pn=this.TF=null:(this.TF=new g.i2(this.Wl,void 0,this),g.W(this,this.TF),this.Pn=new g.Ko(this.d1,2E3,this),g.W(this,this.Pn));g.W(this,this.zF);g.hC(this.player,this.j.element,4);g.W(this,this.j);
this.N||this.zF.Z(K,"resize",this.vn);H=g.wo(this.Qg)&&!g.HN()&&!this.D.isFullscreen();r=this.Qg.Sk().K.s5(g.cV4)&&g.KZ(this.Qg)&&g.Fc;(this.V6=(H||r)&&!this.N&&!this.KK)&&this.zF.Z(K,H?"resize":"fullscreentoggled",this.XH);this.zF.Z(K,"onPlaybackAudioChange",this.Pl);this.zF.Z(K,g.e9("captions"),O=>{this.onCueRangeEnter(O)});
this.zF.Z(K,g.o8("captions"),O=>{this.onCueRangeExit(O)});
tX(this,Zs()||{});g.Y7(this.player,"onCaptionsModuleAvailable");this.B==="HLS"&&this.N&&(K=this.D.hq().zL(),this.Ay&&this.zF.Z(K.textTracks,"addtrack",this.kS))}Vg(){if(this.N||this.KK){let K=this.D.hq();K&&!K.Md()&&K.j()}else lk(this,!1);super.Vg()}H3(){return this.Qg.O("html5_honor_caption_availabilities_in_audio_track")&&this.B!=="LIVE"&&this.B!=="SABR_LIVE"}Df(){if(this.wZ)return this.N||this.KK;if(this.B==="HLS")return this.N;var K=this.getAudioTrack();if(this.H3()){if(!K.captionTracks.length)return!1;
if(!this.K)return!0}K=vJ(K,g.SR(this.Qg));return K==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:K==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?CK(this):zW(this)||CK(this)?!0:P25(this)}load(){super.load();this.C=this.getAudioTrack();if(this.K)this.Y&&(this.jk.clear(),this.N?gTq(this,!0):this.player.getPresentingPlayerType()!==3&&this.K.N(this.Y,"json3",this.fK),this.B!=="HLS"&&this.N||this.KK||JX(this)||g.Y7(this.player,"captionschanged",g.vK(this.Y)));else{let K;this.B==="OFFLINE"?K=new HoS(this.player,this.videoData,
this.getAudioTrack()):this.B==="SABR_LIVE"?K=new kax(this.videoData.K,this.player):this.B==="HLS"?K=new zwK(this.player):this.B==="LIVE"?K=new s45(this.videoData.K,this.player):this.B==="INNERTUBE"?K=new g.z2(this.player,this.videoData,this.getAudioTrack()):K=new g.CE(this.player,this.videoData.jk,this.videoData.videoId,g.aEM(this.videoData),this.videoData.oj,this.videoData.eventId);this.K=K;g.W(this,this.K);this.K.V(this.fK)}}unload(){this.N&&this.Y?gTq(this,!1):(this.Pn&&this.Pn.J2(),this.player.sN("captions"),
this.iG=[],this.K&&this.K.B(),this.jk.clear(),this.Ib&&this.player.No(this.Ib),this.vn());super.unload();this.player.nh();g.Y7(this.player,"captionschanged",{})}create(){this.Df()&&this.load();var K;a:{if(this.Qg.O("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(K=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let H of K)if(H.kind==="asr"&&H.languageCode===
"en"){K=!0;break a}K=!1}K&&this.D.publish("showpromotooltip",this.j.element)}fL(){var K=vJ(this.player.getAudioTrack(),g.SR(this.Qg));K=K==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?aK(this,this.G):K==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&CK(this)?mR(this):zW(this)||this.G||P25(this)?aK(this,this.G):CK(this)?mR(this):null;this.B!=="HLS"&&this.N||this.KK?NXL(this,K):(!this.Y&&K&&uk(this,K),g.Y7(this.player,"onCaptionsTrackListChanged"),g.U3(this.player,"onApiChange"))}CE(){var K=this.D.hq().zL().textTracks,
H=null;for(let r=0;r<K.length;r++)if(K[r].mode==="showing")a:{H=g.gM(this.K.K,!0);for(let O=0;O<H.length;O++)if(H[O].toString()===K[r].id){H=H[O];break a}H=null}(this.loaded?this.Y:null)!==H&&uk(this,H,!0)}kS(){this.K?.V(this.fK)}Wb(){!this.Y&&this.N||this.unload()}qp(K,H,r,O){if(K){hX(this,this.Y??void 0);this.K.KK()&&(this.iG=[],this.D.sN("captions"),BJ(this.TF),this.jk.reset());a:{var A=this.jk;O=O||0;r=oTB(A,K,r||0);K=[];try{for(let z of r){let m=z.trackData,a=z.NA,n=A.Qg.O("safari_live_drm_captions_fix");
if(typeof m!=="string"){r=K;var k=r.concat;if(n&&IMG(m))var b=wV4(A,m,a);else{var D=A,y=H,B=m,Z=a,F=O;if(!K2o(B))throw Error("Invalid binary caption track data");D.K||(D.K=new Ooq(F,y));b=D.K.B(B,Z)}var X=k.call(r,b)}else{if(m.substring(0,6)==="WEBVTT")var w=K.concat(wV4(A,m,a));else{r=K;var T=r.concat;b:{y=A;D=H;if(m[0]==="{")try{y.K||(y.K=new KZQ(dRB(D)));var S=y.K.B(m,a);break b}catch($N){g.ts($N);S=[];break b}let r4=g.C8(m);if(!r4||!r4.firstChild){let $N=Error("Invalid caption track data");$N.params=
m;throw $N;}if(r4.firstChild.tagName==="timedtext"){if(Number(r4.firstChild.getAttribute("format"))===3){B=r4;y.K||(y.K=new Rw4(dRB(D)));S=y.K.B(B,a);break b}let $N=Error("Unsupported subtitles format in web player (Format2)");$N.params=m;throw $N;}if(r4.firstChild.tagName==="transcript"){let $N=Error("Unsupported subtitles format in web player (Format1)");$N.params=m;throw $N;}let Xd=Error("Invalid caption track data");Xd.params=m;throw Xd;}w=T.call(r,S)}X=w}K=X}var G=K;break a}catch(z){g.xe(A.logger,
187101178,`Captions parsing failed: ${z.message}. `);A.clear();G=[];break a}G=void 0}this.Qg.O("html5_sabr_live_support_subfragmented_captions")&&this.K instanceof kax&&(H=this.K.Ib,A=[],G.length>0&&(A=G.slice(H.B.length)),H.B=!H.K||H.K.info.WI?[]:G,G=A);G.length>0&&(H=this.Y,this.Fq(H,!!H,JX(this)?"g":this.G?"m":"s"));this.player.No(G,void 0,this.B==="LIVE"||this.B==="SABR_LIVE");!this.G||this.KK||JX(this)||g.rE(this.Qg)||g.XO(this.Qg)||g.rh(this.Qg)||this.Qg.zF==="shortspage"||this.player.isInline()||
(this.Pn.J2(),G=ndK({CZ:0,G2:5,md:5,So:2,textAlign:0,M3:0,lang:"en"}),this.O5=[G],H=["Click "," for settings"],this.Jy||(A=new g.LM(g.VU()),g.W(this,A),this.Jy=A.element),A=G.end-G.start,(X=g.BK(this.Y))&&this.O5.push(new TW(G.start,A,0,G.id,X)),this.O5.push(new TW(G.start,A,0,G.id,H[0]),new TW(G.start,A,0,G.id,this.Jy,!0),new TW(G.start,A,0,G.id,H[1],!0)),this.player.No(this.O5),g.Hp(this.Pn));!this.G||this.KK||JX(this)||(this.Qg.O("enable_player_captions_persistence_state_machine")?GW(this,!0):
g.SR(this.Qg)?fK(this,!0):nK(this,!0),this.C&&(this.C.N=this.Y),this.player.nh());this.G=!1}}onCueRangeEnter(K){this.iG.push(K);BJ(this.TF)}onCueRangeExit(K){g.b0(this.iG,K);this.K instanceof s45&&this.K.Bn&&this.player.T4([K]);BJ(this.TF)}getCaptionWindowContainerId(){return this.j.element.id}d1(){ETB(this,this.O5);this.O5=null}Wl(){if(!this.V6||!this.N){this.TF.stop();g.Jx(this.hy);this.iG.sort(g.Fq);var K=this.iG;if(this.Ib){let H=g.aP(K,function(r){return this.Ib.indexOf(r)===-1},this);
H.length&&(K=H)}for(let H of K)H instanceof Es?UR4(this,H):SLB(this,H);for(let [H,r]of Object.entries(this.Nd)){let O=H,A=r;this.hy[O]?(A.element.parentNode||(A instanceof lMo||A instanceof tZK||g.L5(this.Nd,(k,b)=>{b!==O&&k.Y.params.CZ===A.Y.params.CZ&&k.Y.params.G2===A.Y.params.G2&&k.Y.params.md===A.Y.params.md&&(k.dispose(),delete this.Nd[b]);return b===O},this),this.j.element.appendChild(A.element)),A.j(this.hy[O])):(A.dispose(),delete this.Nd[O])}}}Ld(){tX(this,{},!0);
g.Y7(this.player,"captionssettingschanged")}QE(){var K=this.Qg.O("enable_player_captions_new_style_defaults")?TXK:Q4Y,H=K.zZ;K={background:H.background,backgroundOpacity:H.backgroundOpacity,charEdgeStyle:H.charEdgeStyle,color:H.color,fontFamily:H.fontFamily,fontSizeIncrement:H.fontSizeIncrement,fontStyle:H.bold&&H.italic?3:H.bold?1:H.italic?2:0,textOpacity:H.textOpacity,windowColor:K.windowColor,windowOpacity:K.windowOpacity};H=Zs()||{};H.background!=null&&(K.background=H.background);H.backgroundOverride!=
null&&(K.backgroundOverride=H.backgroundOverride);H.backgroundOpacity!=null&&(K.backgroundOpacity=H.backgroundOpacity);H.backgroundOpacityOverride!=null&&(K.backgroundOpacityOverride=H.backgroundOpacityOverride);H.charEdgeStyle!=null&&(K.charEdgeStyle=H.charEdgeStyle);H.charEdgeStyleOverride!=null&&(K.charEdgeStyleOverride=H.charEdgeStyleOverride);H.color!=null&&(K.color=H.color);H.colorOverride!=null&&(K.colorOverride=H.colorOverride);H.fontFamily!=null&&(K.fontFamily=H.fontFamily);H.fontFamilyOverride!=
null&&(K.fontFamilyOverride=H.fontFamilyOverride);H.fontSizeIncrement!=null&&(K.fontSizeIncrement=H.fontSizeIncrement);H.fontSizeIncrementOverride!=null&&(K.fontSizeIncrementOverride=H.fontSizeIncrementOverride);H.fontStyle!=null&&(K.fontStyle=H.fontStyle);H.fontStyleOverride!=null&&(K.fontStyleOverride=H.fontStyleOverride);H.textOpacity!=null&&(K.textOpacity=H.textOpacity);H.textOpacityOverride!=null&&(K.textOpacityOverride=H.textOpacityOverride);H.windowColor!=null&&(K.windowColor=H.windowColor);
H.windowColorOverride!=null&&(K.windowColorOverride=H.windowColorOverride);H.windowOpacity!=null&&(K.windowOpacity=H.windowOpacity);H.windowOpacityOverride!=null&&(K.windowOpacityOverride=H.windowOpacityOverride);return K}vz(K,H){var r={};Object.assign(r,Zs());Object.assign(r,K);tX(this,r,H);g.Y7(this.player,"captionssettingschanged")}vn(){!this.N&&this.loaded&&(g.$G(this.Nd,function(K,H){K.dispose();delete this.Nd[H]},this),this.Wl())}SH(K,H){switch(K){case "fontSize":if(isNaN(H))break;
K=g.Pv(H,-2,4);this.vz({fontSizeIncrement:K});return K;case "reload":H&&!this.N&&uk(this,this.Y,!0);break;case "stickyLoading":H!==void 0&&this.Qg.Ib&&(this.Qg.O("enable_player_captions_persistence_state_machine")?GW(this,!(!H||!H.userInitiated)):g.SR(this.Qg)?fK(this,!!H):nK(this,!!H));break;case "track":return W2Q(this,H);case "tracklist":return this.K?g.nO(g.gM(this.K.K,!(!H||!H.includeAsr)),r=>g.vK(r)):[];
case "translationLanguages":return this.K?this.K.C.map(r=>Object.assign({},r)):[];
case "sampleSubtitles":this.N||H===void 0||lk(this,!!H);break;case "sampleSubtitlesCustomized":this.N||lk(this,!!H,H);break;case "recommendedTranslationLanguages":return g.Ob();case "defaultTranslationSourceTrackIndices":return this.K?this.K.Nd:[]}}getOptions(){var K="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Qg.Ib&&K.push("stickyLoading");return K}X9(){var K=this.Y;if(this.D.QX("captions")){if(this.Qg.O("html5_modify_caption_vss_logging"))return(K=this.videoData.Yj??
null)?{cc:g.Vg9(K)}:{};if(K){let H=K.vssId;K.translationLanguage&&H&&(H=`t${H}.${g.IQ(K)}`);return{cc:H}}}return{}}Ks(K){this.isSubtitlesOn()?(this.Qg.O("enable_player_captions_persistence_state_machine")&&K?GW(this,!1):g.SR(this.Qg)?fK(this,!1):nK(this,!1),hX(this),uk(this,null,!0)):this.O_(K)}O_(K){var H=JX(this)||!this.Y?aK(this,!0):this.Y;H&&this.mK(H.vssId,"m");this.isSubtitlesOn()||uk(this,H,this.Qg.O("enable_player_captions_persistence_state_machine")?K:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.Y&&!JX(this)}Pl(){var K=JX(this);CK(this,K)?uk(this,this.getAudioTrack().K,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.H3()&&(this.G=!1,this.Y=null,this.K&&(this.K.dispose(),this.K=null)),this.Df()&&(K?uk(this,aK(this,!1),!1):this.load()))}W0(K){K&&(this.Bn={top:K.top,right:K.right,bottom:K.bottom,left:K.left,width:1-K.left-K.right,height:1-K.top-K.bottom},this.j.element.style.top=`${this.Bn.top*100}%`,this.j.element.style.left=`${this.Bn.left*100}%`,this.j.element.style.width=
`${this.Bn.width*100}%`,this.j.element.style.height=`${this.Bn.height*100}%`,this.j.element.style.position="absolute",K=VZx(this))&&(this.j.element.style.width=`${K.width}px`,this.j.element.style.height=`${K.height}px`)}onVideoDataChange(K,H){K==="newdata"&&(this.videoData=H,this.loaded&&this.unload(),this.G=!1,this.Y=null,this.K&&(this.K.dispose(),this.K=null,g.Y7(this.player,"captionschanged",{})),this.Df()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}XH(){if(this.Qg.Sk().K.s5(g.cV4)){this.loaded&&
this.unload();var K=this.D.hq();K&&!K.Md()&&K.j();this.wZ=this.D.isFullscreen()||this.Qg.controlsType==="3";this.N=Vp(this);this.KK=cj0(this);this.K&&(this.N||this.KK)&&NXL(this,null)}else(K=this.D.hq())&&!K.Md()&&K.j(),this.D.isFullscreen()?(this.N=this.wZ=!0,this.loaded&&this.fL()):(this.wZ=this.Qg.controlsType==="3",this.N=Vp(this));uk(this,this.Y)}ZE(){var K=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;K&&g.P6(this.player,"innertubeCommand",
K)}Fq(K,H,r){var O=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,A="";K&&(A=K.vssId,A=A.replace(O,""));var k="";K&&K.getId()&&(k=K.getId()||"");K&&K.getXtags()&&(K=K.getXtags(),K=K.replace(O,""),k=k.concat(`;${K}`));this.B==="HLS"&&(k="");this.D.Fq(H?A:"",H?k:"",r)}mK(K,H){K=(K||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");K.length>0&&this.D.mK(K,H)}});})(_yt_player);
