(function(g){var window=this;'use strict';var Uqx=function(K,H){g.P6(K,"onAutonavCoundownStarted",H)},Su0=function(K){return K.isBackground()&&K.pg()},V5L=function(K,H){H=H.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
K.KK=H?.navigationEndpoint;H=H?.trackingParams;K.playButton&&H&&K.D.setTrackingParams(K.playButton.element,H)},MF=function(K){var H=yb(K),r=Math,O=r.min;
var A=K.G?Date.now()-K.G:0;r=O.call(r,A,H);jx(K,Math.ceil((H-r)/1E3));H-r<=500&&K.K()?K.select(!0):K.K()&&K.j.start()},jx=function(K,H=-1){K=K.Y.Rb("ytp-autonav-endscreen-upnext-header");
g.yz(K);if(H>=0){H=String(H);let O="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],A="Up next in $SECONDS".indexOf(O);if(A>=0){var r=g.bn("Up next in $SECONDS".slice(0,A));K.appendChild(r);r=g.ka("span");g.kM(r,"ytp-autonav-endscreen-upnext-header-countdown-number");g.vQ(r,H);K.appendChild(r);H=g.bn("Up next in $SECONDS".slice(A+O.length));K.appendChild(H);return}}g.vQ(K,"Up next")},yb=function(K){return K.D.isFullscreen()?(K=K.D.getVideoData().Eu,K===-1||K===void 0?8E3:K):K.D.QY()>=0?K.D.QY():
K.D.X().experiments.K("autoplay_time")||1E4},BM=function(K,H){H=t54(K,H);
var r=Math,O=r.min;var A=(0,g.f)()-K.G;r=O.call(r,A,H);H=H===0?1:Math.min(r/H,1);K.iG.setAttribute("stroke-dashoffset",`${-211*(H+1)}`);H>=1&&K.K()&&!K.isCasting()?K.select(!0):K.K()&&K.Y.start()},t54=function(K,H){return H?H:K.api.isFullscreen()?(K=K.api.getVideoData().Eu,K===-1||K===void 0?8E3:K):K.api.QY()>=0?K.api.QY():K.api.X().experiments.K("autoplay_time")||1E4},vM=function(K){return g.uj(K.player)&&K.G()&&!K.B},I2=function(K){var H=K.CQ();
H!==K.j&&(K.j=H,K.player.publish("autonavvisibility"))},Zt=function(K){return g.uj(K.player)&&K.G()&&!K.N},Ft=function(K){var H=K.CQ();
H!==K.KK&&(K.KK=H,K.player.publish("autonavvisibility"))},lBY=function(K){K=K.X();
return K.ug&&!K.disableOrganicUi},WZK=function(K){var H=K.player.getVideoData();
if(!H||K.K===H.aE)return!1;K.K=H.aE;return!0},Gao=function(K){K.player.sN("endscreen");
var H=K.player.getVideoData();H=new g.bZ(Math.max((H.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var r=new g.bZ(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});K.player.No([H,r])};
g.IB.prototype.QY=g.AH(15,function(){return this.app.QY()});
g.r7.prototype.QY=g.AH(14,function(){return this.getVideoData().Eb});
g.ve.prototype.oh=g.AH(13,function(K){this.rd().oh(K)});
g.nw.prototype.oh=g.AH(12,function(K){this.Vf!==K&&(this.Vf=K,this.Pv())});
var ex=class extends g.R{constructor(K){super({L:"div",S:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.KK=void 0;this.G=0;K.O("web_post_play_autonav_embiggening")&&g.DB(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.R({L:"div",S:"ytp-autonav-endscreen-countdown-container"});g.W(this,this.container);this.container.Hn(this.element);var H=K.X(),r=H.N;this.D=K;this.suggestion=null;this.onVideoDataChange("newdata",this.D.getVideoData());this.Z(K,"videodatachange",
this.onVideoDataChange);this.Y=new g.R({L:"div",S:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},J:[{L:"div",S:"ytp-autonav-endscreen-topbar-container",J:[{L:"div",S:"ytp-autonav-endscreen-upnext-header"},{L:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",ek:"{{autoplayAlternativeHeader}}"}]},{L:"a",S:"ytp-autonav-endscreen-link-container",
U:{href:"{{url}}",target:r?H.Bn:""},J:[{L:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},J:[{L:"div",U:{"aria-label":"{{timestamp}}"},ob:["ytp-autonav-timestamp"],ek:"{{duration}}"},{L:"div",ob:["ytp-autonav-live-stamp"],ek:"Live"},{L:"div",ob:["ytp-autonav-upcoming-stamp"],ek:"Upcoming"}]},{L:"div",S:"ytp-autonav-endscreen-video-info",J:[{L:"div",S:"ytp-autonav-endscreen-premium-badge"},{L:"div",S:"ytp-autonav-endscreen-upnext-title",ek:"{{title}}"},{L:"div",S:"ytp-autonav-endscreen-upnext-author",
ek:"{{author}}"},{L:"div",S:"ytp-autonav-view-and-date",ek:"{{views_and_publish_time}}"},{L:"div",S:"ytp-autonav-author-and-view",ek:"{{author_and_views}}"}]}]}]});g.W(this,this.Y);this.Y.Hn(this.container.element);r||this.Z(this.Y.Rb("ytp-autonav-endscreen-link-container"),"click",this.zF);this.D.createClientVe(this.container.element,this,115127);this.D.createClientVe(this.Y.Rb("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.R({L:"button",S:"ytp-autonav-endscreen-upnext-header-close-button",
U:{"aria-label":"Cancel autoplay"}});g.W(this,this.closeButton);K.O("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.Nd,this),this.D.createClientVe(this.closeButton.element,this,115129),this.Y.Rb("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.R({L:"div",S:"ytp-autonav-overlay"});g.W(this,this.overlay);this.overlay.Hn(this.container.element);this.W=new g.R({L:"div",S:"ytp-autonav-endscreen-button-container"});g.W(this,
this.W);this.W.Hn(this.container.element);this.cancelButton=new g.R({L:"button",ob:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],U:{"aria-label":"Cancel autoplay"},ek:"Cancel"});g.W(this,this.cancelButton);this.cancelButton.Hn(this.W.element);this.cancelButton.listen("click",this.Nd,this);this.D.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.R({L:"a",ob:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],U:{href:"{{url}}",role:"button","aria-label":"Play next video"},ek:"Play Now"});g.W(this,this.playButton);this.playButton.Hn(this.W.element);this.playButton.listen("click",this.zF,this);this.D.createServerVe(this.playButton.element,this.playButton,!0);(H=this.D.getVideoData())&&V5L(this,H);this.j=new g.Ko(()=>{MF(this)},500);
g.W(this,this.j);this.Bn();this.Z(K,"autonavvisibility",this.Bn)}C(K){this.suggestion!==K&&(this.suggestion=K,g.VN(this.Y,K),this.playButton.updateValue("url",this.suggestion.PL()),this.redraw())}redraw(){var K=this.D.EO(!0,this.D.isFullscreen());g.Bp(this.container.element,"ytp-autonav-endscreen-small-mode",this.ea(K));g.Bp(this.container.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.kq);g.Bp(this.D.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.D.CQ());
g.Bp(this.D.getRootNode(),"countdown-running",this.K());g.Bp(this.container.element,"ytp-player-content",this.D.CQ());this.D.O("web_post_play_autonav_embiggening")||g.Ut(this.overlay.element,{width:`${K.width}px`});if(this.D.O("web_post_play_autonav_embiggening")){var H=this.D.getRootNode().getBoundingClientRect();K=Math.min(720,H.width*.5);var r=K*.5625;H=H.height-36-60;r>H&&(r=H,K=16/9*r);g.Ut(this.Y.Rb("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${r}px`,width:`${K}px`});g.Ut(this.container.element,
{width:`${K}px`})}this.K()||(this.D.CQ()?jx(this,Math.round(yb(this)/1E3)):jx(this),K=!!this.suggestion&&!!this.suggestion.xs,r=this.D.getVideoData(),r=r.autonavState===1&&r.E1&&this.D.CQ()?!1:this.D.CQ()||!(this.suggestion&&this.suggestion.xs),g.Bp(this.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!r&&K),g.Bp(this.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",r&&!K),this.W.Au(this.D.CQ()))}K(){return this.G>0}V(){this.K()||(this.G=Date.now(),MF(this),
Uqx(this.D,yb(this)),g.Bp(this.D.getRootNode(),"countdown-running",this.K()))}N(){this.B();MF(this);var K=this.Y.Rb("ytp-autonav-endscreen-upnext-header");K&&g.vQ(K,"Up next")}B(){this.K()&&(this.j.stop(),this.G=0)}select(K=!1){this.D.nextVideo(!1,K);this.B()}zF(K){g.BI(K,this.D)&&(K.currentTarget===this.playButton.element?this.D.logClick(this.playButton.element):K.currentTarget===this.Y.Rb("ytp-autonav-endscreen-link-container")&&(K=this.Y.Rb("ytp-autonav-endscreen-link-container"),this.D.logVisibility(K,
!0),this.D.logClick(K)),this.KK?(g.P6(this.D,"innertubeCommand",this.KK),this.B()):this.select())}Nd(){this.D.logClick(this.cancelButton.element);g.JC(this.D,!0);this.cancelCommand&&g.P6(this.D,"innertubeCommand",this.cancelCommand)}onVideoDataChange(K,H){V5L(this,H);this.cancelCommand=H.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}Bn(){var K=this.D.CQ();this.TL!==K&&this.Au(K);this.redraw();this.D.logVisibility(this.container.element,
K);this.D.logVisibility(this.cancelButton.element,K);this.D.logVisibility(this.Y.Rb("ytp-autonav-endscreen-link-container"),K);this.D.logVisibility(this.playButton.element,K)}ea(K){return K.width<400||K.height<459}};var o2=class extends g.R{constructor(K,H){super({L:"div",ob:["html5-endscreen","ytp-player-content",H||"base-endscreen"]});this.created=!1;this.player=K}create(){this.created=!0}destroy(){this.created=!1}G(){return!1}CQ(){return!1}C(){return!1}};var zWu=class extends g.R{constructor(K){super({L:"div",ob:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},J:[{L:"div",S:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{L:"span",S:"ytp-upnext-top",J:[{L:"span",S:"ytp-upnext-header",ek:"Up Next"},{L:"span",S:"ytp-upnext-title",ek:"{{title}}"},{L:"span",S:"ytp-upnext-author",ek:"{{author}}"}]},{L:"a",S:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{L:"svg",U:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{L:"circle",S:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{L:"circle",S:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{L:"path",S:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{L:"span",S:"ytp-upnext-bottom",J:[{L:"span",S:"ytp-upnext-cancel"},
{L:"span",S:"ytp-upnext-paused",ek:"Autoplay is paused"}]}]});this.api=K;this.cancelButton=null;this.iG=this.Rb("ytp-svg-autoplay-ring");this.j=this.notification=this.Y=this.suggestion=null;this.KK=new g.Ko(this.W,5E3,this);this.G=0;var H=this.Rb("ytp-upnext-cancel");this.cancelButton=new g.R({L:"button",ob:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},ek:"Cancel"});g.W(this,this.cancelButton);this.cancelButton.listen("click",this.Nd,this);this.cancelButton.Hn(H);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.W(this,this.KK);this.api.createClientVe(this.element,this,18788);H=this.Rb("ytp-upnext-autoplay-icon");this.Z(H,"click",this.zF);this.api.createClientVe(H,this,115130);this.Bn();this.Z(K,"autonavvisibility",this.Bn);this.Z(K,"mdxnowautoplaying",this.TF);this.Z(K,"mdxautoplaycanceled",this.wZ);g.Bp(this.element,"ytp-upnext-mobile",this.api.X().B)}W(){this.notification&&(this.KK.stop(),this.OE(this.j),this.j=null,this.notification.close(),
this.notification=null)}C(K){this.suggestion=K;g.VN(this,K,"hqdefault.jpg")}Bn(){this.Au(this.api.CQ());this.api.logVisibility(this.element,this.api.CQ());this.api.logVisibility(this.Rb("ytp-upnext-autoplay-icon"),this.api.CQ());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.CQ())}Pn(){window.focus();this.W()}V(K){this.K()||(g.Bj("a11y-announce",`Up Next ${this.suggestion.title}`),this.G=(0,g.f)(),this.Y=new g.Ko(()=>{BM(this,K)},25),BM(this,K),Uqx(this.api,t54(this,
K)));
g.j5(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}K(){return!!this.Y}isCasting(){return this.api.getPresentingPlayerType()===3}N(){this.B();this.G=(0,g.f)();BM(this);g.DB(this.element,"ytp-upnext-autoplay-paused")}B(){this.K()&&(this.Y.dispose(),this.Y=null)}select(K=!1){if(this.api.X().O("autonav_notifications")&&K&&window.Notification&&typeof document.hasFocus==="function"){let H=Notification.permission;H==="default"?Notification.requestPermission():H!=="granted"||document.hasFocus()||
(this.W(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.bF()}),this.j=this.Z(this.notification,"click",this.Pn),this.KK.start())}this.B();this.api.nextVideo(!1,K)}zF(K){!g.BQ(this.cancelButton.element,K.target)&&g.BI(K,this.api)&&(this.api.CQ()&&this.api.logClick(this.Rb("ytp-upnext-autoplay-icon")),this.select())}Nd(){this.api.CQ()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.JC(this.api,!0)}TF(K){this.isCasting();this.show();
this.V(K)}wZ(){this.isCasting();this.B();this.hide()}Vg(){this.B();this.W();super.Vg()}};var CdB=class extends o2{constructor(K){super(K,"videowall-endscreen");this.D=K;this.stills=[];this.B=this.videoData=null;this.N=this.j=!1;this.KK=null;g.DB(this.element,"modern-videowall-endscreen");this.Y=new g.Zc(this);g.W(this,this.Y);this.V=new g.Ko(()=>{g.DB(this.element,"ytp-show-tiles")},0);
g.W(this,this.V);this.table=new g.LM({L:"div",S:"ytp-modern-endscreen-content"});g.W(this,this.table);this.table.Hn(this.element);K.getVideoData().aE?this.K=new ex(K):this.K=new zWu(K);g.W(this,this.K);g.hC(this.player,this.K.element,4);K.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var K=this.player.getVideoData();K&&(this.videoData=K);this.redraw();this.Y.Z(this.player,"appresize",this.redraw);this.Y.Z(this.player,"onVideoAreaChange",this.redraw);this.Y.Z(this.player,
"videodatachange",this.onVideoDataChange);this.Y.Z(this.player,"autonavchange",this.W);this.Y.Z(this.player,"onAutonavCancelled",this.Bn);K=this.videoData.autonavState;K!==this.KK&&this.W(K,!1);this.Y.Z(this.element,"transitionend",this.Nd)}destroy(){this.Y.Y();g.g5(this.stills);this.stills=[];super.destroy();g.j5(this.element,"ytp-show-tiles");this.V.stop();this.KK=this.videoData.autonavState}G(){return this.videoData?.E1||this.videoData.autonavState!==1}show(){var K=this.TL;super.show();g.j5(this.element,
"ytp-show-tiles");this.player.X().B?g.rb(this.V):this.V.start();(this.N||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.JC(this.player,!1);vM(this)?(I2(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||Su0(this.player.ZR())&&this.player.O("web_player_pip_logging_fix")?this.K.select(!0):this.K.V():this.videoData.autonavState===3&&this.K.N()):(g.JC(this.player,!0),I2(this));K!==this.TL&&this.player.logVisibility(this.element,!0)}hide(){var K=this.TL;super.hide();this.K.N();
I2(this);K!==this.TL&&this.player.logVisibility(this.element,!1)}Nd(K){K.target===this.element&&this.redraw()}redraw(){var K=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.j()];if(K.length){var H=this.D.EO(!0,this.D.isFullscreen()),r=Math.floor((H.width-64+16)/(g.Pv(H.width*.27,250,450)+16));H=Math.min(3,Math.floor((H.height-64)/((H.width-64-(r-1)*16)/r*.5625+70)));g.Mq(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.DB(this.element,`ytp-modern-endscreen-limit-rows-${H}`);g.Bp(this.element,"ytp-modern-endscreen-single-item",r===1);g.Bp(this.element,"ytp-modern-endscreen-row-0",H===0);r=this.table.element;r.ariaLive="polite";this.K.C(this.videoData.j());this.K instanceof ex&&this.K.redraw();g.Bp(this.element,"ytp-endscreen-takeover",vM(this));I2(this);H=0;r.ariaBusy="true";var O=K.length;for(let A=0;A<O;A++){let k=A%O,b=this.stills[A];b||(b=new g.nA0(this.player),this.stills[A]=b,r.appendChild(b.element));g.LtM(b,
K[k]);H++}this.stills.length=H}}onVideoDataChange(){var K=this.player.getVideoData({playerType:1});this.videoData!==K&&(K?.j()?(this.videoData=K,this.redraw()):this.player.Yv("missg",{vid:K?.videoId||"",cpn:K?.clientPlaybackNonce||""}))}C(){return this.K.K()}W(K,H=!1){var r=this.videoData?.E1;if(K===1){if(!r||H)this.N=!1,this.B=this.videoData.clientPlaybackNonce;this.K.B();this.TL&&this.redraw()}else this.N=!0,this.TL&&vM(this)&&(K===2?this.K.V():K===3&&this.K.N())}Bn(K){if(K){for(K=0;K<this.stills.length;K++)this.D.logVisibility(this.stills[K].element,
!0);this.W(1,!0)}else this.B=null,this.N=!1;this.redraw()}CQ(){return this.TL&&vM(this)}};var JRu=class extends g.R{constructor(K){var H=K.X(),r=g.AA||g.G0?{style:"will-change: opacity"}:void 0,O=H.N,A=["ytp-videowall-still"];H.B&&A.push("ytp-videowall-show-text");super({L:"a",ob:A,U:{href:"{{url}}",target:O?H.Bn:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{L:"div",S:"ytp-videowall-still-image",U:{style:"{{background}}"}},{L:"span",S:"ytp-videowall-still-info",U:{"aria-hidden":"true"},J:[{L:"span",S:"ytp-videowall-still-info-bg",
J:[{L:"span",S:"ytp-videowall-still-info-content",U:r,J:[{L:"span",S:"ytp-videowall-still-info-title",ek:"{{title}}"},{L:"span",S:"ytp-videowall-still-info-author",ek:"{{author_and_views}}"},{L:"span",S:"ytp-videowall-still-info-live",ek:"Live"},{L:"span",S:"ytp-videowall-still-info-duration",ek:"{{duration}}"}]}]}]},{L:"span",ob:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:{"aria-hidden":"true"},J:[{L:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{L:"span",
S:"ytp-videowall-still-listlabel-length",J:[" (",{L:"span",ek:"{{playlist_length}}"},")"]}]},{L:"span",ob:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],U:{"aria-hidden":"true"},J:[{L:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{L:"span",S:"ytp-videowall-still-listlabel-length",ek:" (50+)"}]}]});this.suggestion=null;this.Y=O;this.api=K;this.K=new g.Zc(this);g.W(this,this.K);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.K.Z(K,"videodatachange",
this.onVideoDataChange);K.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.v9(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.W5||void 0)&&this.api.logClick(this.element)}onClick(K){if(g.Q8(this.api.X())&&this.api.O("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let H=this.suggestion.PL(),r={};g.fs(this.api,r);H=g.a6(H,r);g.vI(H,this.api,K)}else g.BI(K,this.api,
this.Y,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(K){switch(K.keyCode){case 13:case 32:K.defaultPrevented||(this.select(),K.preventDefault())}}onVideoDataChange(){var K=this.api.getVideoData(),H=this.api.X();this.Y=K.NQ?!1:H.N}};var scB=class extends o2{constructor(K){super(K,"videowall-endscreen");this.D=K;this.B=0;this.stills=[];this.N=this.videoData=null;this.V=this.KK=!1;this.Bn=null;this.Y=new g.Zc(this);g.W(this,this.Y);this.W=new g.Ko(()=>{g.DB(this.element,"ytp-show-tiles")},0);
g.W(this,this.W);var H=new g.R({L:"button",ob:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},J:[g.cC()]});g.W(this,H);H.Hn(this.element);H.listen("click",this.iG,this);this.table=new g.LM({L:"div",S:"ytp-endscreen-content"});g.W(this,this.table);this.table.Hn(this.element);H=new g.R({L:"button",ob:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Next"},J:[g.Tw()]});g.W(this,H);H.Hn(this.element);H.listen("click",this.zF,this);K.getVideoData().aE?this.K=new ex(K):this.K=new zWu(K);
g.W(this,this.K);g.hC(this.player,this.K.element,4);K.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var K=this.player.getVideoData();K&&(this.videoData=K);this.redraw();this.Y.Z(this.player,"appresize",this.redraw);this.Y.Z(this.player,"onVideoAreaChange",this.redraw);this.Y.Z(this.player,"videodatachange",this.onVideoDataChange);this.Y.Z(this.player,"autonavchange",this.j);this.Y.Z(this.player,"onAutonavCancelled",this.Nd);K=this.videoData.autonavState;K!==this.Bn&&
this.j(K,!1);this.Y.Z(this.element,"transitionend",this.TF)}destroy(){this.Y.Y();g.g5(this.stills);this.stills=[];super.destroy();g.j5(this.element,"ytp-show-tiles");this.W.stop();this.Bn=this.videoData.autonavState}G(){return this.videoData?.E1||this.videoData?.autonavState!==1}show(){var K=this.TL;super.show();g.j5(this.element,"ytp-show-tiles");this.player.X().B?g.rb(this.W):this.W.start();(this.V||this.N&&this.N!==this.videoData.clientPlaybackNonce)&&g.JC(this.player,!1);Zt(this)?(Ft(this),this.videoData.autonavState===
2?this.player.getVisibilityState()===3||Su0(this.player.ZR())&&this.player.O("web_player_pip_logging_fix")?this.K.select(!0):this.K.V():this.videoData.autonavState===3&&this.K.N()):(g.JC(this.player,!0),Ft(this));K!==this.TL&&this.player.logVisibility(this.element,!0)}hide(){var K=this.TL;super.hide();this.K.N();Ft(this);K!==this.TL&&this.player.logVisibility(this.element,!1)}TF(K){K.target===this.element&&this.redraw()}redraw(){var K=this.videoData?.suggestions?.length?this.videoData?.suggestions:
[this.videoData?.j()];if(K.length){g.DB(this.element,"ytp-endscreen-paginate");var H=this.D.EO(!0,this.D.isFullscreen()),r=g.Vv(this.D);r&&(r=r.Cg()?48:32,H.width-=r*2);var O=H.width/H.height,A=96/54,k=r=2,b=Math.max(H.width/96,2),D=Math.max(H.height/54,2),y=K.length;var B=y*4;for(B-=4;B>0&&(r<b||k<D);){var Z=r/2,F=k/2,X=r<=b-2&&B>=F*4,w=k<=D-2&&B>=Z*4;if((Z+1)/F*A/O>O/(Z/(F+1)*A)&&w)B-=Z*4,k+=2;else if(X)B-=F*4,r+=2;else if(w)B-=Z*4,k+=2;else break}A=!1;B>=12&&y*4-B<=6&&(k>=4||r>=4)&&(A=!0);B=r*
96;b=k*54;O=B/b<O?H.height/b:H.width/B;O=Math.min(O,2);B=Math.floor(Math.min(H.width,B*O));b=Math.floor(Math.min(H.height,b*O));H=this.table.element;H.ariaLive="polite";g.qu(H,B,b);g.Ut(H,{marginLeft:`${B/-2}px`,marginTop:`${b/-2}px`});this.K.C(this.videoData.j());this.K instanceof ex&&this.K.redraw();g.Bp(this.element,"ytp-endscreen-takeover",Zt(this));Ft(this);B+=4;b+=4;O=0;H.ariaBusy="true";for(D=0;D<r;D++)for(Z=0;Z<k;Z++)if(X=O,w=0,A&&D>=r-2&&Z>=k-2?w=1:Z%2===0&&D%2===0&&(Z<2&&D<2?Z===0&&D===
0&&(w=2):w=2),X=g.gO(X+this.B,y),w!==0){F=this.stills[O];F||(F=new JRu(this.player),this.stills[O]=F,H.appendChild(F.element));var T=Math.floor(b*Z/k);let S=Math.floor(B*D/r),G=Math.floor(b*(Z+w)/k)-T-4,z=Math.floor(B*(D+w)/r)-S-4;g.C3(F.element,S,T);g.qu(F.element,z,G);g.Ut(F.element,"transitionDelay",(Z+D)/20+"s");g.Bp(F.element,"ytp-videowall-still-mini",w===1);g.Bp(F.element,"ytp-videowall-still-large",w>2);w=Math.max(z,G);g.Bp(F.element,"ytp-videowall-still-round-large",w>=256);g.Bp(F.element,
"ytp-videowall-still-round-medium",w>96&&w<256);g.Bp(F.element,"ytp-videowall-still-round-small",w<=96);X=K[X];F.suggestion!==X&&(F.suggestion=X,w=F.api.X(),T=g.bd(F.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.VN(F,X,T),g.Q8(w)&&!F.api.O("web_player_log_click_before_generating_ve_conversion_params")&&(w=X.PL(),T={},g.N0(F.api,"addEmbedsConversionTrackingParams",[T]),w=g.a6(w,T),F.updateValue("url",w)),(X=(X=X.sessionData)&&X.itct)&&F.api.setTrackingParams(F.element,X));
O++}H.ariaBusy="false";g.Bp(this.element,"ytp-endscreen-paginate",O<y);for(K=this.stills.length-1;K>=O;K--)r=this.stills[K],g.Mu(r.element),g.P3(r);this.stills.length=O}}onVideoDataChange(){var K=this.player.getVideoData({playerType:1});this.videoData!==K&&(K?.j()?(this.B=0,this.videoData=K,this.redraw()):this.player.Yv("missg",{vid:K?.videoId||"",cpn:K?.clientPlaybackNonce||""}))}zF(){this.B+=this.stills.length;this.redraw()}iG(){this.B-=this.stills.length;this.redraw()}C(){return this.K.K()}j(K,
H=!1){var r=this.videoData?.E1;if(K===1){if(!r||H)this.V=!1,this.N=this.videoData.clientPlaybackNonce;this.K.B();this.TL&&this.redraw()}else this.V=!0,this.TL&&Zt(this)&&(K===2?this.K.V():K===3&&this.K.N())}Nd(K){if(K){for(K=0;K<this.stills.length;K++)this.D.logVisibility(this.stills[K].element,!0);this.j(1,!0)}else this.N=null,this.V=!1;this.redraw()}CQ(){return this.TL&&Zt(this)}};var mqG=class extends g.R{constructor(K){super({L:"button",ob:["ytp-watch-on-youtube-button","ytp-button"],ek:"{{content}}"});this.D=K;this.buttonType=this.buttonType=1;this.K();this.buttonType===2&&g.DB(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.K);this.Au(!0)}K(){switch(this.buttonType){case 1:var K="Watch again on YouTube";var H=156915;break;case 2:K="Continue watching on YouTube";H=156942;break;default:K="Continue watching on YouTube",
H=156942}this.update({content:K});this.D.hasVe(this.element)&&this.D.destroyVe(this.element);this.D.createClientVe(this.element,this,H)}onClick(K){this.D.O("web_player_log_click_before_generating_ve_conversion_params")&&this.D.logClick(this.element);g.vI(this.getVideoUrl(),this.D,K);this.D.O("web_player_log_click_before_generating_ve_conversion_params")||this.D.logClick(this.element)}getVideoUrl(){var K=!0;switch(this.buttonType){case 1:K=!0;break;case 2:K=!1}K=this.D.getVideoUrl(K,!1,!1,!0);var H=
this.D.X();if(g.Q8(H)){let r={};g.Q8(H)&&g.N0(this.D,"addEmbedsConversionTrackingParams",[r]);K=g.a6(K,r)}return K}logVisibility(){this.D.logVisibility(this.element,this.TL&&this.Ib)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}WD(K){super.WD(K);this.logVisibility()}};var aBS=class extends o2{constructor(K){super(K,"watch-again-on-youtube-endscreen");this.watchButton=new mqG(K);g.W(this,this.watchButton);this.watchButton.Hn(this.element);g.$FN(K)&&(this.K=new g.UbS(K),g.W(this,this.K),this.Y=new g.R({L:"div",ob:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],U:{tabIndex:"-1"},J:[this.K]}),g.W(this,this.Y),this.K.Hn(this.Y.element),this.Y.Hn(this.element));K.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.K?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let H=this.Y;if(H){var K=this.K.hasSuggestions();g.Bp(this.element,"ytp-shorts-branded-ui",K);K?H.show():H.hide()}g.Vv(this.player)?.oh(!0);this.player.logVisibility(this.element,!0);this.watchButton.WD(!0)}}hide(){super.hide();g.Vv(this.player)?.oh(!1);this.player.logVisibility(this.element,!1);this.watchButton.WD(!1)}};g.u4("endscreen",class extends g.We{constructor(K){super(K);this.endScreen=null;this.K=this.Y=!1;this.listeners=new g.Zc(this);g.W(this,this.listeners);var H=K.X();K.isEmbedsShortsMode()?this.endScreen=new aBS(K):lBY(K)?(this.Y=!0,WZK(this),H.O("delhi_modern_endscreen")?this.endScreen=new CdB(K):this.endScreen=new scB(K)):this.endScreen=new o2(K);g.W(this,this.endScreen);g.hC(K,this.endScreen.element,4);Gao(this);this.listeners.Z(K,"videodatachange",this.onVideoDataChange,this);this.listeners.Z(K,
g.e9("endscreen"),r=>{this.onCueRangeEnter(r)});
this.listeners.Z(K,g.o8("endscreen"),r=>{this.onCueRangeExit(r)})}Df(){var K=this.player.getVideoData(),H=K.mutedAutoplay&&(K.limitedPlaybackDurationInSeconds>0||K.endSeconds>0||K.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!H)return!0;var r=!(!K.j()&&!K.suggestions?.length);r=!lBY(this.player)||r;var O=K.CA,A=this.player.kp();return(r||!!K?.E1)&&!O&&!A&&!H}CQ(){return this.endScreen.CQ()}Uc(){return this.CQ()?this.endScreen.C():!1}Vg(){this.player.sN("endscreen");super.Vg()}load(){{let r=this.player.getVideoData(),O=r.transitionEndpointAtEndOfStream;if(O&&O.videoId){var K=this.player.mI().GZ.get("heartbeat");var H=r.j();!H||O.videoId!==H.videoId||r.Ox?(this.player.v9(O.videoId,void 0,
void 0,!0,!0,O),K&&K.q_("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),K=!0):K=!1}else K=!1}K||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(K){this.Df()&&(this.endScreen.created||this.endScreen.create(),K.getId()==="load"&&this.load())}onCueRangeExit(K){K.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){Gao(this);this.Y&&WZK(this)&&(this.endScreen&&
(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new scB(this.player),g.W(this,this.endScreen),g.hC(this.player,this.endScreen.element,4))}});})(_yt_player);
